import type { ProviderKind } from "../protocol/protocol.js";
export interface ProviderSpec {
  kind: ProviderKind;
  label: string;
  tags: string[];
  defaultBaseUrl?: string;
}
export const PROVIDERS: ProviderSpec[] = [
  { tags: ["gpt","chatgpt"], kind: "openai", label: "OpenAI", defaultBaseUrl: "https://api.openai.com/v1" },
  { tags: ["generic","custom"], kind: "openai-compatible", label: "OpenAI-compatible" },
  { tags: ["vscode","local"], kind: "vscode-lm", label: "VS Code Language Models" },
  { tags: ["router","multi-model"], kind: "tokenrouter", label: "TokenRouter", defaultBaseUrl: "https://api.tokenrouter.com/v1" },
  { tags: ["01","yi","zeroone"], kind: "zeroone", label: "01.AI (Yi)", defaultBaseUrl: "https://api.01.ai/v1" },
  { tags: ["302","302ai"], kind: "302ai", label: "302.AI", defaultBaseUrl: "https://api.302.ai/v1" },
  { tags: ["abacus"], kind: "abacus", label: "Abacus", defaultBaseUrl: "https://routellm.abacus.ai/v1" },
  { tags: ["abliteration"], kind: "abliteration-ai", label: "abliteration.ai", defaultBaseUrl: "https://api.abliteration.ai/v1" },
  { tags: ["aibadgr","badgr"], kind: "aibadgr", label: "AI Badgr", defaultBaseUrl: "https://aibadgr.com/api/v1" },
  { tags: ["router"], kind: "ai-router", label: "AI-ROUTER", defaultBaseUrl: "https://api.ai-router.dev/v1" },
  { tags: ["aiml","ml"], kind: "aiml-api", label: "AI/ML API", defaultBaseUrl: "https://api.aimlapi.com/v1" },
  { tags: ["aiand"], kind: "aiand", label: "ai&", defaultBaseUrl: "https://api.aiand.com/v1" },
  { tags: ["ai21","labs"], kind: "ai21", label: "AI21 Labs", defaultBaseUrl: "https://api.ai21.com/studio/v1" },
  { tags: ["aki","io"], kind: "aki-io", label: "AKI.IO", defaultBaseUrl: "https://aki.io/v1" },
  { tags: ["aleph","alpha"], kind: "aleph-alpha", label: "Aleph Alpha", defaultBaseUrl: "https://api.aleph-alpha.com/v1" },
  { tags: ["alibaba"], kind: "alibaba", label: "Alibaba", defaultBaseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1" },
  { tags: ["alibaba","coding","plan"], kind: "alibaba-coding-plan", label: "Alibaba Coding Plan", defaultBaseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1" },
  { tags: ["alibaba","china","cn","coding","plan"], kind: "alibaba-coding-plan-cn", label: "Alibaba Coding Plan (China)", defaultBaseUrl: "https://coding.dashscope.aliyuncs.com/v1" },
  { tags: ["alibaba","dashscope","qwen"], kind: "dashscope", label: "Alibaba DashScope (Qwen)", defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1" },
  { tags: ["alibaba","plan","token","token-plan"], kind: "alibaba-token-plan", label: "Alibaba Token Plan", defaultBaseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1" },
  { tags: ["alibaba","china","cn","plan","token","token-plan"], kind: "alibaba-token-plan-cn", label: "Alibaba Token Plan (China)", defaultBaseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1" },
  { tags: ["amazon","aws","bedrock"], kind: "aws-bedrock", label: "Amazon Bedrock", defaultBaseUrl: "https://bedrock-runtime.{region}.amazonaws.com/openai/v1" },
  { tags: ["amazon","aws","bedrock","mantle"], kind: "aws-bedrock-mantle", label: "Amazon Bedrock (Mantle)", defaultBaseUrl: "https://bedrock-mantle.{region}.api.aws/openai/v1" },
  { tags: ["ambient"], kind: "ambient", label: "Ambient", defaultBaseUrl: "https://api.ambient.xyz/v1" },
  { tags: ["anthropic","claude","fable","opus","sonnet"], kind: "anthropic", label: "Anthropic", defaultBaseUrl: "https://api.anthropic.com/v1" },
  { tags: ["any","control","llm","plane"], kind: "any-llm", label: "Any-LLM Control Plane", defaultBaseUrl: "https://api.any-llm.com/v1" },
  { tags: ["anyapi"], kind: "anyapi", label: "AnyAPI", defaultBaseUrl: "https://api.anyapi.ai/v1" },
  { tags: ["anyscale","endpoints"], kind: "anyscale", label: "Anyscale Endpoints", defaultBaseUrl: "https://api.endpoints.anyscale.com/v1" },
  { tags: ["apertis","apexit"], kind: "apexit", label: "Apertis AI", defaultBaseUrl: "https://api.apertis.ai/v1" },
  { tags: ["aphrodite","engine","local"], kind: "aphrodite", label: "Aphrodite Engine", defaultBaseUrl: "http://localhost:2242/v1" },
  { tags: ["apiyi"], kind: "apiyi", label: "APIYI", defaultBaseUrl: "https://api.apiyi.com/v1" },
  { tags: ["atomic","chat","local"], kind: "atomic-chat", label: "Atomic Chat", defaultBaseUrl: "http://127.0.0.1:1337/v1" },
  { tags: ["auriko"], kind: "auriko", label: "Auriko", defaultBaseUrl: "https://api.auriko.ai/v1" },
  { tags: ["azure","foundry"], kind: "azure-foundry", label: "Azure AI Foundry", defaultBaseUrl: "https://{resourceName}.services.ai.azure.com/openai/v1" },
  { tags: ["azure","openai"], kind: "azure-openai", label: "Azure OpenAI", defaultBaseUrl: "https://{resourceName}.openai.azure.com/openai/v1" },
  { tags: ["baichuan"], kind: "baichuan", label: "Baichuan AI", defaultBaseUrl: "https://api.baichuan-ai.com/v1" },
  { tags: ["baidu","qianfan"], kind: "baidu-qianfan", label: "Baidu Qianfan", defaultBaseUrl: "https://qianfan.baidubce.com/v2" },
  { tags: ["baidu","qianfan"], kind: "baidu-qianfan-ai", label: "Baidu Qianfan AI", defaultBaseUrl: "https://api.baiduqianfan.ai/v1" },
  { tags: ["bailing"], kind: "bailing", label: "Bailing", defaultBaseUrl: "https://api.tbox.cn/api/llm/v1/chat/completions" },
  { tags: ["apis","baseten","model"], kind: "baseten", label: "Baseten (Model APIs)", defaultBaseUrl: "https://inference.baseten.co/v1" },
  { tags: ["berget"], kind: "berget", label: "Berget.AI", defaultBaseUrl: "https://api.berget.ai/v1" },
  { tags: ["bifrost"], kind: "bifrost", label: "Bifrost AI", defaultBaseUrl: "https://api.bifrost.ai/v1" },
  { tags: ["bfl","black","forest","labs"], kind: "bfl", label: "Black Forest Labs", defaultBaseUrl: "https://api.bfl.ai/v1" },
  { tags: ["blue","blueclaw","claw"], kind: "blueclaw", label: "Blue Claw", defaultBaseUrl: "https://openai.blueclaw.network/v1" },
  { tags: ["braintrust","gateway","router"], kind: "braintrust", label: "Braintrust Gateway", defaultBaseUrl: "https://api.braintrust.dev/v1" },
  { tags: ["byteplus","modelark"], kind: "byteplus", label: "Byteplus ModelArk", defaultBaseUrl: "https://ark.ap-southeast-bytepluses.com/api/v3" },
  { tags: ["bytez"], kind: "bytez", label: "Bytez", defaultBaseUrl: "https://api.bytez.com/v1" },
  { tags: ["cerebras"], kind: "cerebras", label: "Cerebras", defaultBaseUrl: "https://api.cerebras.ai/v1" },
  { tags: ["charm","hyper"], kind: "hyper", label: "Charm Hyper", defaultBaseUrl: "https://hyper.charm.land/v1" },
  { tags: ["chutes"], kind: "chutes", label: "Chutes AI", defaultBaseUrl: "https://api.chutes.ai/v1" },
  { tags: ["clarifai"], kind: "clarifai", label: "Clarifai", defaultBaseUrl: "https://api.clarifai.com/v2/ext/openai/v1" },
  { tags: ["claudinio"], kind: "claudinio", label: "Claudinio", defaultBaseUrl: "https://api.claudin.io/v1" },
  { tags: ["cline","clinepass","pass"], kind: "cline-pass", label: "ClinePass", defaultBaseUrl: "https://api.cline.bot/api/v1" },
  { tags: ["cloudferro","sherlock"], kind: "cloudferro-sherlock", label: "CloudFerro Sherlock", defaultBaseUrl: "https://api-sherlock.cloudferro.com/openai/v1" },
  { tags: ["cloudflare","workers"], kind: "cloudflare-workers-ai", label: "Cloudflare Workers AI", defaultBaseUrl: "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1" },
  { tags: ["aya","cohere","command"], kind: "cohere", label: "Cohere", defaultBaseUrl: "https://api.cohere.ai/compatibility/v1" },
  { tags: ["comet"], kind: "comet-api", label: "Comet API", defaultBaseUrl: "https://api.comet.com/v1" },
  { tags: ["compactifai"], kind: "compactifai", label: "CompactifAI", defaultBaseUrl: "https://api.compactif.ai/v1" },
  { tags: ["coralbricks"], kind: "coralbricks", label: "CoralBricks", defaultBaseUrl: "https://inference.coralbricks.ai/v1" },
  { tags: ["cortecs"], kind: "cortecs", label: "Cortecs", defaultBaseUrl: "https://api.cortecs.ai/v1" },
  { tags: ["crof","crofai"], kind: "crof", label: "CrofAI", defaultBaseUrl: "https://crof.ai/v1" },
  { tags: ["crossmodel"], kind: "crossmodel", label: "CrossModel", defaultBaseUrl: "https://api.crossmodel.ai/v1" },
  { tags: ["china","drun","run"], kind: "drun", label: "D.Run (China)", defaultBaseUrl: "https://chat.d.run/v1" },
  { tags: ["daoxe"], kind: "daoxe", label: "DaoXE", defaultBaseUrl: "https://daoxe.com/v1" },
  { tags: ["databricks","model","serving"], kind: "databricks", label: "Databricks Model Serving", defaultBaseUrl: "https://{workspace-url}/serving-endpoints" },
  { tags: ["datarobot"], kind: "datarobot", label: "DataRobot", defaultBaseUrl: "https://app.datarobot.com/api/v1" },
  { tags: ["decart"], kind: "decart", label: "Decart AI", defaultBaseUrl: "https://api.decart.ai/v1" },
  { tags: ["deepgram","text"], kind: "deepgram", label: "Deepgram (Text)", defaultBaseUrl: "https://api.deepgram.com/v1" },
  { tags: ["deepinfra"], kind: "deepinfra", label: "DeepInfra", defaultBaseUrl: "https://api.deepinfra.com/v1/openai" },
  { tags: ["deepseek","v4"], kind: "deepseek", label: "DeepSeek", defaultBaseUrl: "https://api.deepseek.com/v1" },
  { tags: ["digitalocean"], kind: "digitalocean", label: "DigitalOcean", defaultBaseUrl: "https://inference.do-ai.run/v1" },
  { tags: ["dinference"], kind: "dinference", label: "DInference", defaultBaseUrl: "https://api.dinference.com/v1" },
  { tags: ["ebcloud"], kind: "ebcloud", label: "EBCloud", defaultBaseUrl: "https://maas-api.ebcloud.com/v1" },
  { tags: ["eden","edenai"], kind: "edenai", label: "Eden AI", defaultBaseUrl: "https://api.edenai.run/v2" },
  { tags: ["elevenlabs","text"], kind: "elevenlabs", label: "ElevenLabs (Text)", defaultBaseUrl: "https://api.elevenlabs.io/v1" },
  { tags: ["empiriolabs"], kind: "empiriolabs", label: "EmpirioLabs AI", defaultBaseUrl: "https://api.empiriolabs.ai/v1" },
  { tags: ["evroc"], kind: "evroc", label: "evroc", defaultBaseUrl: "https://models.think.evroc.com/v1" },
  { tags: ["fal"], kind: "fal", label: "Fal.ai", defaultBaseUrl: "https://queue.fal.run" },
  { tags: ["fastrouter","router"], kind: "fastrouter", label: "FastRouter", defaultBaseUrl: "https://go.fastrouter.ai/api/v1" },
  { tags: ["featherless"], kind: "featherless", label: "Featherless AI", defaultBaseUrl: "https://api.featherless.ai/v1" },
  { tags: ["fireworks"], kind: "fireworks", label: "Fireworks AI", defaultBaseUrl: "https://api.fireworks.ai/inference/v1" },
  { tags: ["freemodel"], kind: "freemodel", label: "FreeModel", defaultBaseUrl: "https://cc.freemodel.dev/v1" },
  { tags: ["friendli","friendliai"], kind: "friendli", label: "FriendliAI", defaultBaseUrl: "https://api.friendli.ai/v1" },
  { tags: ["frogbot"], kind: "frogbot", label: "FrogBot", defaultBaseUrl: "https://app.frogbot.ai/api/v1" },
  { tags: ["galadriel"], kind: "galadriel", label: "Galadriel", defaultBaseUrl: "https://api.galadriel.com/v1" },
  { tags: ["copilot","github"], kind: "github-copilot", label: "GitHub Copilot", defaultBaseUrl: "https://api.githubcopilot.com" },
  { tags: ["github","models"], kind: "github-models", label: "GitHub Models", defaultBaseUrl: "https://models.inference.ai.azure.com" },
  { tags: ["cloud","gmi"], kind: "gmi-cloud", label: "GMI Cloud", defaultBaseUrl: "https://api.gmicloud.ai/v1" },
  { tags: ["bard","deepmind","gemini","gemma","google"], kind: "google", label: "Google AI", defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta/openai" },
  { tags: ["cloud","gcp","google","vertex"], kind: "gcp-vertex", label: "Google Cloud Vertex AI", defaultBaseUrl: "https://{region}-aiplatform.googleapis.com/v1/projects/{project_id}/locations/{location}/endpoints/openapi" },
  { tags: ["gpt4all","local"], kind: "gpt4all", label: "GPT4All", defaultBaseUrl: "http://localhost:4891/v1" },
  { tags: ["gradient","gradientai"], kind: "gradientai", label: "Gradient AI", defaultBaseUrl: "https://api.gradient.ai/v1" },
  { tags: ["greenpt"], kind: "greenpt", label: "GreenPT", defaultBaseUrl: "https://api.greenpt.ai/v1" },
  { tags: ["fast","groq"], kind: "groq", label: "Groq", defaultBaseUrl: "https://api.groq.com/openai/v1" },
  { tags: ["helicone","router"], kind: "helicone", label: "Helicone", defaultBaseUrl: "https://gateway.helicone.ai/v1" },
  { tags: ["heroku"], kind: "heroku", label: "Heroku AI", defaultBaseUrl: "https://api.heroku.com/ai/v1" },
  { tags: ["hetzner"], kind: "hetzner", label: "Hetzner", defaultBaseUrl: "https://inference.hetzner.com/api/v1" },
  { tags: ["hpc"], kind: "hpc-ai", label: "HPC-AI", defaultBaseUrl: "https://api.hpc-ai.com/inference/v1" },
  { tags: ["face","hf","hugging","huggingface","inference","router"], kind: "huggingface", label: "Hugging Face Inference", defaultBaseUrl: "https://router.huggingface.co/v1" },
  { tags: ["hyperbolic"], kind: "hyperbolic", label: "Hyperbolic AI", defaultBaseUrl: "https://api.hyperbolic.xyz/v1" },
  { tags: ["ibm","watsonx"], kind: "ibm-watsonx", label: "IBM watsonx.ai", defaultBaseUrl: "https://{region}.ml.cloud.ibm.com/ml/v1" },
  { tags: ["iflow","iflowcn"], kind: "iflowcn", label: "iFlow", defaultBaseUrl: "https://apis.iflow.cn/v1" },
  { tags: ["impossibl"], kind: "impossibl", label: "Impossibl", defaultBaseUrl: "https://api.impossibl.com/v1" },
  { tags: ["inception"], kind: "inception", label: "Inception AI", defaultBaseUrl: "https://api.inception.ai/v1" },
  { tags: ["inceptron"], kind: "inceptron", label: "Inceptron", defaultBaseUrl: "https://api.inceptron.io/v1" },
  { tags: ["inference"], kind: "inference", label: "Inference", defaultBaseUrl: "https://inference.net/v1" },
  { tags: ["inferx"], kind: "inferx", label: "InferX", defaultBaseUrl: "https://model.inferx.net/endpoints/v1" },
  { tags: ["infomaniak"], kind: "infomaniak", label: "Infomaniak", defaultBaseUrl: "https://api.infomaniak.com/2/ai/${INFOMANIAK_PRODUCT_ID}/openai/v1" },
  { tags: ["io","net"], kind: "io-net", label: "IO.NET", defaultBaseUrl: "https://api.intelligence.io.solutions/api/v1" },
  { tags: ["jan","local"], kind: "jan", label: "Jan (Local)", defaultBaseUrl: "http://localhost:1337/v1" },
  { tags: ["jiekou"], kind: "jiekou", label: "Jiekou.AI", defaultBaseUrl: "https://api.jiekou.ai/openai" },
  { tags: ["jina"], kind: "jina", label: "Jina AI", defaultBaseUrl: "https://api.jina.ai/v1" },
  { tags: ["kenari"], kind: "kenari", label: "Kenari", defaultBaseUrl: "https://kenari.id/v1" },
  { tags: ["gateway","kilo","router"], kind: "kilo-gateway", label: "Kilo Gateway", defaultBaseUrl: "https://api.kilo.ai/api/gateway" },
  { tags: ["kimi","moonshot"], kind: "kimi", label: "Kimi", defaultBaseUrl: "https://api.moonshot.ai/v1" },
  { tags: ["cn","kimi","moonshot"], kind: "kimi-cn", label: "Kimi (CN)", defaultBaseUrl: "https://api.moonshot.cn/v1" },
  { tags: ["coding","kimi","moonshot"], kind: "kimi-for-coding", label: "Kimi For Coding", defaultBaseUrl: "https://api.kimi.com/coding/v1" },
  { tags: ["kluster"], kind: "kluster-ai", label: "Kluster AI", defaultBaseUrl: "https://api.kluster.ai/v1" },
  { tags: ["koboldcpp","local"], kind: "koboldcpp", label: "KoboldCPP", defaultBaseUrl: "http://localhost:5001/v1" },
  { tags: ["cloud","coding","kuae","plan"], kind: "kuae-cloud-coding-plan", label: "KUAE Cloud Coding Plan", defaultBaseUrl: "https://coding-plan-endpoint.kuaecloud.net/v1" },
  { tags: ["lambda"], kind: "lambda-ai", label: "Lambda AI", defaultBaseUrl: "https://api.lambda.ai/v1" },
  { tags: ["laozhang"], kind: "laozhang", label: "LaoZhang API", defaultBaseUrl: "https://api.laozhang.ai/v1" },
  { tags: ["lemonade","local","server"], kind: "lemonade", label: "Lemonade Server", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["lepton"], kind: "lepton", label: "Lepton AI", defaultBaseUrl: "https://api.lepton.ai/api/v1" },
  { tags: ["lilac"], kind: "lilac", label: "Lilac", defaultBaseUrl: "https://api.getlilac.com/v1" },
  { tags: ["litellm","local","proxy","router"], kind: "litellm-proxy", label: "LiteLLM Proxy", defaultBaseUrl: "http://localhost:4000/v1" },
  { tags: ["llama"], kind: "llama-api", label: "Llama API", defaultBaseUrl: "https://api.llama.com/compat/v1" },
  { tags: ["cpp","llama","local","server"], kind: "llama-cpp", label: "llama.cpp / llama-server", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["llamafile","local"], kind: "llamafile", label: "Llamafile", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["llamagate"], kind: "llamagate", label: "LlamaGate", defaultBaseUrl: "https://api.llamagate.com/v1" },
  { tags: ["gateway","llm","llmgateway","router"], kind: "llmgateway", label: "LLM Gateway", defaultBaseUrl: "https://api.llmgateway.io/v1" },
  { tags: ["llmtr"], kind: "llmtr", label: "LLMTR", defaultBaseUrl: "https://llmtr.com/v1" },
  { tags: ["lm","local","studio"], kind: "lm-studio", label: "LM Studio (Local)", defaultBaseUrl: "http://localhost:1234/v1" },
  { tags: ["local","localai"], kind: "localai", label: "LocalAI", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["longcat"], kind: "longcat", label: "LongCat", defaultBaseUrl: "https://api.longcat.chat/openai" },
  { tags: ["lucidquery"], kind: "lucidquery", label: "LucidQuery", defaultBaseUrl: "https://api.lucidquery.com/v1" },
  { tags: ["local","lynkr"], kind: "lynkr", label: "Lynkr", defaultBaseUrl: "http://127.0.0.1:8081/v1" },
  { tags: ["manus"], kind: "manus", label: "Manus AI", defaultBaseUrl: "https://api.manus.ai/v1" },
  { tags: ["martian"], kind: "martian", label: "Martian", defaultBaseUrl: "https://api.withmartian.com/v1" },
  { tags: ["meganova"], kind: "meganova", label: "Meganova", defaultBaseUrl: "https://api.meganova.ai/v1" },
  { tags: ["llama","meta"], kind: "meta", label: "Meta", defaultBaseUrl: "https://api.meta.ai/v1" },
  { tags: ["minimax"], kind: "minimax", label: "MiniMax", defaultBaseUrl: "https://api.minimax.io/v1" },
  { tags: ["cn","minimax"], kind: "minimax-cn", label: "MiniMax (CN)", defaultBaseUrl: "https://api.minimaxi.com/v1" },
  { tags: ["coding","io","minimax","plan","token","token-plan"], kind: "minimax-coding-plan", label: "MiniMax Token Plan (minimax.io)", defaultBaseUrl: "https://api.minimax.io/anthropic/v1" },
  { tags: ["cn","coding","com","minimax","minimaxi","plan","token","token-plan"], kind: "minimax-cn-coding-plan", label: "MiniMax Token Plan (minimaxi.com)", defaultBaseUrl: "https://api.minimaxi.com/anthropic/v1" },
  { tags: ["codestral","devstral","mistral","mixtral"], kind: "mistral", label: "Mistral", defaultBaseUrl: "https://api.mistral.ai/v1" },
  { tags: ["mixlayer"], kind: "mixlayer", label: "Mixlayer", defaultBaseUrl: "https://models.mixlayer.ai/v1" },
  { tags: ["moark"], kind: "moark", label: "Moark", defaultBaseUrl: "https://moark.com/v1" },
  { tags: ["modal"], kind: "modal", label: "Modal", defaultBaseUrl: "https://inference.us-west.modal.direct/v1" },
  { tags: ["model","oracle"], kind: "model-oracle-ai", label: "Model Oracle AI", defaultBaseUrl: "https://api.modeloracle.com/api/v1" },
  { tags: ["modelis"], kind: "modelis", label: "Modelis", defaultBaseUrl: "https://modelishub.com/v1" },
  { tags: ["modelscope"], kind: "modelscope", label: "ModelScope", defaultBaseUrl: "https://api-inference.modelscope.cn/v1" },
  { tags: ["modelslab"], kind: "modelslab", label: "ModelsLab", defaultBaseUrl: "https://modelslab.com/api/v1" },
  { tags: ["chat","morph"], kind: "morph", label: "Morph Chat", defaultBaseUrl: "https://api.morph.chat/v1" },
  { tags: ["nanogpt"], kind: "nanogpt", label: "NanoGPT", defaultBaseUrl: "https://nano-gpt.com/api/v1" },
  { tags: ["cloud","near"], kind: "near-ai", label: "NEAR AI Cloud", defaultBaseUrl: "https://api.near.ai/v1" },
  { tags: ["factory","nebius","token"], kind: "nebius", label: "Nebius Token Factory", defaultBaseUrl: "https://api.tokenfactory.nebius.com/v1" },
  { tags: ["neon","router"], kind: "neon", label: "Neon", defaultBaseUrl: "${NEON_AI_GATEWAY_BASE_URL}/v1" },
  { tags: ["neuralwatt"], kind: "neuralwatt", label: "Neuralwatt", defaultBaseUrl: "https://api.neuralwatt.com/v1" },
  { tags: ["local","new"], kind: "new-api", label: "New API", defaultBaseUrl: "http://localhost:3000/v1" },
  { tags: ["cloud","nlp"], kind: "nlp-cloud", label: "NLP Cloud", defaultBaseUrl: "https://api.nlpcloud.com/v1" },
  { tags: ["nova"], kind: "nova", label: "Nova", defaultBaseUrl: "https://api.nova.amazon.com/v1" },
  { tags: ["novita"], kind: "novita", label: "Novita AI", defaultBaseUrl: "https://api.novita.ai/v1" },
  { tags: ["nscale"], kind: "nscale", label: "Nscale", defaultBaseUrl: "https://api.nscale.com/v1" },
  { tags: ["catalog","nim","nvidia"], kind: "nvidia", label: "NVIDIA API Catalog", defaultBaseUrl: "https://integrate.api.nvidia.com/v1" },
  { tags: ["ofox"], kind: "ofox", label: "Ofox", defaultBaseUrl: "https://api.ofox.ai/v1" },
  { tags: ["local","ollama"], kind: "ollama", label: "Ollama", defaultBaseUrl: "http://127.0.0.1:11434" },
  { tags: ["cloud","ollama"], kind: "ollama-cloud", label: "Ollama Cloud", defaultBaseUrl: "https://ollama.com/v1" },
  { tags: ["local","one"], kind: "one-api", label: "One API", defaultBaseUrl: "http://localhost:3000/v1" },
  { tags: ["go","opencode"], kind: "opencode-go", label: "OpenCode Go", defaultBaseUrl: "https://opencode.ai/zen/go/v1" },
  { tags: ["opencode","zen"], kind: "opencode", label: "OpenCode Zen", defaultBaseUrl: "https://opencode.ai/zen/v1" },
  { tags: ["multi-model","openrouter","router"], kind: "openrouter", label: "OpenRouter", defaultBaseUrl: "https://openrouter.ai/api/v1" },
  { tags: ["cloud","genai","infrastructure","oci","oracle"], kind: "oracle-oci", label: "Oracle Cloud Infrastructure GenAI", defaultBaseUrl: "https://generativeai.oci.oraclecloud.com" },
  { tags: ["orcarouter","router"], kind: "orcarouter", label: "OrcaRouter", defaultBaseUrl: "https://api.orcarouter.ai/v1" },
  { tags: ["orq"], kind: "orq", label: "Orq.ai", defaultBaseUrl: "https://api.orq.ai/v1" },
  { tags: ["endpoints","ovhcloud"], kind: "ovhcloud", label: "OVHcloud AI Endpoints", defaultBaseUrl: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1" },
  { tags: ["perplexity"], kind: "perplexity", label: "Perplexity", defaultBaseUrl: "https://api.perplexity.ai" },
  { tags: ["agent","perplexity"], kind: "perplexity-agent", label: "Perplexity Agent", defaultBaseUrl: "https://api.perplexity.ai/v1" },
  { tags: ["local","petals"], kind: "petals", label: "Petals", defaultBaseUrl: "http://localhost:8080" },
  { tags: ["pioneer"], kind: "pioneer", label: "Pioneer", defaultBaseUrl: "https://api.pioneer.ai/v1" },
  { tags: ["poe"], kind: "poe", label: "Poe", defaultBaseUrl: "https://api.poe.com/v1" },
  { tags: ["poolside"], kind: "poolside", label: "Poolside", defaultBaseUrl: "https://inference.poolside.ai/v1" },
  { tags: ["portkey"], kind: "portkey", label: "Portkey", defaultBaseUrl: "https://api.portkey.ai/v1" },
  { tags: ["predibase"], kind: "predibase", label: "Predibase", defaultBaseUrl: "https://serving.app.predibase.com" },
  { tags: ["local","privatemode"], kind: "privatemode-ai", label: "Privatemode AI", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["publicai"], kind: "publicai", label: "PublicAI", defaultBaseUrl: "https://api.publicai.com/v1" },
  { tags: ["qihang"], kind: "qihang-ai", label: "QiHang", defaultBaseUrl: "https://api.qhaigc.net/v1" },
  { tags: ["qiniu"], kind: "qiniu-ai", label: "Qiniu", defaultBaseUrl: "https://api.qnaigc.com/v1" },
  { tags: ["recraft"], kind: "recraft", label: "Recraft", defaultBaseUrl: "https://api.recraft.ai/v1" },
  { tags: ["regolo"], kind: "regolo-ai", label: "Regolo AI", defaultBaseUrl: "https://api.regolo.ai/v1" },
  { tags: ["replicate"], kind: "replicate", label: "Replicate", defaultBaseUrl: "https://api.replicate.com/v1" },
  { tags: ["requesty"], kind: "requesty", label: "Requesty", defaultBaseUrl: "https://api.requesty.ai/v1" },
  { tags: ["routing","run"], kind: "routing-run", label: "routing.run", defaultBaseUrl: "https://api.routing.run/v1" },
  { tags: ["runwayml"], kind: "runwayml", label: "RunwayML", defaultBaseUrl: "https://api.runwayml.com/v1" },
  { tags: ["sakana"], kind: "sakana", label: "Sakana AI", defaultBaseUrl: "https://api.sakana.ai/v1" },
  { tags: ["cloud","sambanova"], kind: "sambanova", label: "SambaNova Cloud", defaultBaseUrl: "https://api.sambanova.ai/v1" },
  { tags: ["sarvam"], kind: "sarvam", label: "Sarvam AI", defaultBaseUrl: "https://api.sarvam.ai" },
  { tags: ["apis","generative","scaleway"], kind: "scaleway", label: "Scaleway Generative APIs", defaultBaseUrl: "https://api.scaleway.ai/v1" },
  { tags: ["scx"], kind: "scx", label: "SCX.ai", defaultBaseUrl: "https://api.scx.ai/v1" },
  { tags: ["sensenova"], kind: "sensenova", label: "SenseNova", defaultBaseUrl: "https://api.sensenova.cn/v1" },
  { tags: ["local","sglang"], kind: "sglang", label: "SGLang", defaultBaseUrl: "http://localhost:30000/v1" },
  { tags: ["shareai"], kind: "shareai", label: "ShareAI", defaultBaseUrl: "https://api.shareai.now/v1" },
  { tags: ["siliconflow"], kind: "siliconflow", label: "SiliconFlow", defaultBaseUrl: "https://api.siliconflow.cn/v1" },
  { tags: ["china","cn","siliconflow"], kind: "siliconflow-cn", label: "SiliconFlow (China)", defaultBaseUrl: "https://api.siliconflow.cn/v1" },
  { tags: ["cortex","snowflake"], kind: "snowflake-cortex", label: "Snowflake Cortex", defaultBaseUrl: "https://{account-identifier}.snowflakecomputing.com/api/v1" },
  { tags: ["network","spheron"], kind: "spheron", label: "Spheron Network", defaultBaseUrl: "https://api.spheron.network/v1" },
  { tags: ["stability"], kind: "stability-ai", label: "Stability AI", defaultBaseUrl: "https://api.stability.ai/v1" },
  { tags: ["stackit"], kind: "stackit", label: "STACKIT", defaultBaseUrl: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1" },
  { tags: ["stepfun"], kind: "stepfun", label: "StepFun", defaultBaseUrl: "https://api.stepfun.com/v1" },
  { tags: ["china","plan","step","stepfun"], kind: "stepfun-step-plan", label: "StepFun Step Plan (China)", defaultBaseUrl: "https://api.stepfun.com/step_plan/v1" },
  { tags: ["global","plan","step","stepfun"], kind: "stepfun-ai-step-plan", label: "StepFun Step Plan (Global)", defaultBaseUrl: "https://api.stepfun.ai/step_plan/v1" },
  { tags: ["subconscious"], kind: "subconscious", label: "Subconscious", defaultBaseUrl: "https://api.subconscious.dev/v1" },
  { tags: ["submodel"], kind: "submodel", label: "submodel", defaultBaseUrl: "https://llm.submodel.ai/v1" },
  { tags: ["synthetic"], kind: "synthetic", label: "Synthetic", defaultBaseUrl: "https://api.synthetic.ai/v1" },
  { tags: ["llmhub","systems"], kind: "llmhub", label: "T-Systems LLMhub", defaultBaseUrl: "https://llm-server.llmhub.t-systems.net/v2" },
  { tags: ["assistant","coding","local","tabby"], kind: "tabby", label: "Tabby Coding Assistant", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["inference","telnyx"], kind: "telnyx", label: "Telnyx Inference", defaultBaseUrl: "https://api.telnyx.com/v2/ai" },
  { tags: ["cloud","hunyuan","tencent"], kind: "tencent-cloud", label: "Tencent Cloud Hunyuan", defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1" },
  { tags: ["china","coding","plan","tencent"], kind: "tencent-coding-plan", label: "Tencent Coding Plan (China)", defaultBaseUrl: "https://api.lkeap.cloud.tencent.com/coding/v3" },
  { tags: ["plan","tencent","token","token-plan"], kind: "tencent-token-plan", label: "Tencent Token Plan", defaultBaseUrl: "https://api.lkeap.cloud.tencent.com/plan/v3" },
  { tags: ["tencent","tokenhub"], kind: "tencent-tokenhub", label: "Tencent TokenHub", defaultBaseUrl: "https://tokenhub.tencentmaas.com/v1" },
  { tags: ["tensormesh"], kind: "tensormesh", label: "TensorMesh", defaultBaseUrl: "https://api.tensormesh.ai/v1" },
  { tags: ["tensorx"], kind: "tensorx", label: "TensorX", defaultBaseUrl: "https://api.tensorx.ai/v1" },
  { tags: ["generation","inference","local","text","tgi"], kind: "tgi", label: "Text Generation Inference (TGI)", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["grid"], kind: "the-grid-ai", label: "The Grid AI", defaultBaseUrl: "https://api.thegrid.ai/v1" },
  { tags: ["machines","thinking","thinkingmachines"], kind: "thinkingmachines", label: "Thinking Machines", defaultBaseUrl: "https://tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1" },
  { tags: ["tinfoil"], kind: "tinfoil", label: "Tinfoil", defaultBaseUrl: "https://inference.tinfoil.sh/v1" },
  { tags: ["together"], kind: "together", label: "Together AI", defaultBaseUrl: "https://api.together.xyz/v1" },
  { tags: ["topaz"], kind: "topaz", label: "Topaz AI", defaultBaseUrl: "https://api.topaz.ai/v1" },
  { tags: ["inference","local","server","triton"], kind: "triton-inference", label: "Triton Inference Server", defaultBaseUrl: "http://localhost:8000/v1" },
  { tags: ["router","trustedrouter"], kind: "trustedrouter", label: "TrustedRouter", defaultBaseUrl: "https://api.trustedrouter.com/v1" },
  { tags: ["umans"], kind: "umans-ai", label: "Umans AI", defaultBaseUrl: "https://api.code.umans.ai/v1" },
  { tags: ["coding","plan","umans"], kind: "umans-ai-coding-plan", label: "Umans AI Coding Plan", defaultBaseUrl: "https://api.code.umans.ai/v1" },
  { tags: ["unify"], kind: "unify-ai", label: "Unify AI", defaultBaseUrl: "https://api.unify.ai/v1" },
  { tags: ["router","unorouter"], kind: "unorouter", label: "UnoRouter", defaultBaseUrl: "https://api.unorouter.com/v1" },
  { tags: ["upstage"], kind: "upstage", label: "Upstage AI", defaultBaseUrl: "https://api.upstage.ai/v1" },
  { tags: ["venice"], kind: "venice", label: "Venice.ai", defaultBaseUrl: "https://api.venice.ai/api/v1" },
  { tags: ["gateway","router","vercel"], kind: "vercel", label: "Vercel AI Gateway", defaultBaseUrl: "https://ai-gateway.vercel.sh/v1" },
  { tags: ["v0","vercel"], kind: "v0", label: "Vercel v0", defaultBaseUrl: "https://api.v0.dev/v1" },
  { tags: ["vivgrid"], kind: "vivgrid", label: "Vivgrid", defaultBaseUrl: "https://api.vivgrid.com/v1" },
  { tags: ["local","vllm"], kind: "vllm", label: "vLLM", defaultBaseUrl: "http://localhost:8000/v1" },
  { tags: ["ark","doubao","volcengine"], kind: "volcengine", label: "Volcengine (Doubao / Ark)", defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3" },
  { tags: ["voyage"], kind: "voyage", label: "Voyage AI", defaultBaseUrl: "https://api.voyageai.com/v1" },
  { tags: ["vultr"], kind: "vultr", label: "Vultr", defaultBaseUrl: "https://api.vultrinference.com/v1" },
  { tags: ["wafer"], kind: "wafer.ai", label: "Wafer", defaultBaseUrl: "https://pass.wafer.ai/v1" },
  { tags: ["llm","wavespeed"], kind: "wavespeed", label: "WaveSpeed LLM", defaultBaseUrl: "https://api.wavespeed.ai/v1" },
  { tags: ["biases","inference","wandb","weights"], kind: "wandb-inference", label: "Weights & Biases Inference", defaultBaseUrl: "https://api.wandb.ai/v1" },
  { tags: ["writer"], kind: "writer", label: "Writer API", defaultBaseUrl: "https://api.writer.com/v1" },
  { tags: ["grok","xai"], kind: "xai", label: "xAI", defaultBaseUrl: "https://api.x.ai/v1" },
  { tags: ["mimo","xiaomi"], kind: "xiaomi-mimo", label: "Xiaomi MiMo", defaultBaseUrl: "https://platform.xiaomimimo.com/api/v1" },
  { tags: ["china","cn","plan","token","token-plan","xiaomi"], kind: "xiaomi-token-plan-cn", label: "Xiaomi Token Plan (China)", defaultBaseUrl: "https://token-plan-cn.xiaomimimo.com/v1" },
  { tags: ["ams","europe","plan","token","token-plan","xiaomi"], kind: "xiaomi-token-plan-ams", label: "Xiaomi Token Plan (Europe)", defaultBaseUrl: "https://token-plan-ams.xiaomimimo.com/v1" },
  { tags: ["plan","sgp","singapore","token","token-plan","xiaomi"], kind: "xiaomi-token-plan-sgp", label: "Xiaomi Token Plan (Singapore)", defaultBaseUrl: "https://token-plan-sgp.xiaomimimo.com/v1" },
  { tags: ["local","xinference"], kind: "xinference", label: "Xinference", defaultBaseUrl: "http://localhost:9997/v1" },
  { tags: ["xpersona"], kind: "xpersona", label: "Xpersona", defaultBaseUrl: "https://www.xpersona.co/v1" },
  { tags: ["glm","z","zhipu"], kind: "z-ai", label: "Z.ai", defaultBaseUrl: "https://api.z.ai/api/paas/v4" },
  { tags: ["cn","glm","z","zhipu"], kind: "z-ai-cn", label: "Z.ai (CN)", defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4" },
  { tags: ["coding","glm","plan","zai","zhipu"], kind: "zai-coding-plan", label: "Z.AI Coding Plan", defaultBaseUrl: "https://api.z.ai/api/coding/paas/v4" },
  { tags: ["zeldoc"], kind: "zeldoc", label: "Zeldoc", defaultBaseUrl: "https://api.zeldoc.ai/v1" },
  { tags: ["zenifra"], kind: "zenifra", label: "Zenifra", defaultBaseUrl: "https://ai.zenifra.com/v1" },
  { tags: ["zenmux"], kind: "zenmux", label: "ZenMux", defaultBaseUrl: "https://api.zenmux.com/v1" },
  { tags: ["coding","glm","plan","zhipu","zhipuai"], kind: "zhipuai-coding-plan", label: "Zhipu AI Coding Plan", defaultBaseUrl: "https://open.bigmodel.cn/api/coding/paas/v4" },
];
export function getProviderSpec(kind: ProviderKind): ProviderSpec | undefined {
  return PROVIDERS.find((p) => p.kind === kind);
}