import type { ProviderKind } from "../protocol/protocol.js";
export interface ProviderSpec {
  kind: ProviderKind;
  label: string;
  tags: string[];
  defaultBaseUrl?: string;
}
export const PROVIDERS: ProviderSpec[] = [
<<<<<<< HEAD
  { tags: ["gpt", "chatgpt"], kind: "openai", label: "OpenAI", defaultBaseUrl: "https://api.openai.com/v1", docs: "https://platform.openai.com/docs" },
  { tags: ["router", "multi-model"], kind: "openrouter", label: "OpenRouter", defaultBaseUrl: "https://openrouter.ai/api/v1", docs: "https://openrouter.ai/docs" },
  { tags: ["claude", "sonnet", "opus", "fable"], kind: "anthropic", label: "Anthropic", defaultBaseUrl: "https://api.anthropic.com/v1", docs: "https://docs.anthropic.com" },
  { tags: ["gemini", "gemma", "bard", "palm", "deepmind"], kind: "google", label: "Google AI", defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta/openai", docs: "https://ai.google.dev/gemini-api/docs" },
  { tags: ["groq", "fast inference"], kind: "groq", label: "Groq", defaultBaseUrl: "https://api.groq.com/openai/v1", docs: "https://console.groq.com/docs" },
  { tags: ["mistral", "mixtral", "codestral", "devstral"], kind: "mistral", label: "Mistral", defaultBaseUrl: "https://api.mistral.ai/v1", docs: "https://docs.mistral.ai" },
  { tags: ["deepseek", "v4"], kind: "deepseek", label: "DeepSeek", defaultBaseUrl: "https://api.deepseek.com/v1", docs: "https://api-docs.deepseek.com" },
  { tags: ["grok", "xai"], kind: "xai", label: "xAI", defaultBaseUrl: "https://api.x.ai/v1", docs: "https://docs.x.ai" },
  { tags: ["command", "aya"], kind: "cohere", label: "Cohere", defaultBaseUrl: "https://api.cohere.ai/compatibility/v1", docs: "https://docs.cohere.com" },
  { tags: ["fireworks"], kind: "fireworks", label: "Fireworks AI", defaultBaseUrl: "https://api.fireworks.ai/inference/v1", docs: "https://fireworks.ai/models" },
  { tags: ["together"], kind: "together", label: "Together AI", defaultBaseUrl: "https://api.together.xyz/v1", docs: "https://docs.together.ai" },
  { tags: ["perplexity", "sonar"], kind: "perplexity", label: "Perplexity", defaultBaseUrl: "https://api.perplexity.ai", docs: "https://docs.perplexity.ai" },
  { tags: ["deepinfra"], kind: "deepinfra", label: "DeepInfra", defaultBaseUrl: "https://api.deepinfra.com/v1/openai", docs: "https://deepinfra.com" },
  { tags: ["cerebras"], kind: "cerebras", label: "Cerebras", defaultBaseUrl: "https://api.cerebras.ai/v1", docs: "https://cerebras.ai" },
  { tags: ["local"], kind: "ollama", label: "Ollama", defaultBaseUrl: "http://127.0.0.1:11434", docs: "https://ollama.com" },
  { tags: ["minimax"], kind: "minimax", label: "MiniMax", defaultBaseUrl: "https://api.minimax.io/v1", docs: "https://platform.minimax.io" },
  { tags: ["minimax", "cn"], kind: "minimax-cn", label: "MiniMax (CN)", defaultBaseUrl: "https://api.minimaxi.com/v1", docs: "https://platform.minimax.io" },
  { tags: ["kimi", "moonshot"], kind: "kimi", label: "Kimi", defaultBaseUrl: "https://api.moonshot.ai/v1", docs: "https://platform.moonshot.ai" },
  { tags: ["kimi", "moonshot", "cn"], kind: "kimi-cn", label: "Kimi (CN)", defaultBaseUrl: "https://api.moonshot.cn/v1", docs: "https://platform.moonshot.cn" },
  { tags: ["zhipu", "glm", "z.ai"], kind: "z-ai", label: "Z.ai", defaultBaseUrl: "https://api.z.ai/api/paas/v4", docs: "https://docs.z.ai" },
  { tags: ["zhipu", "glm", "z.ai", "coding plan"], kind: "z-ai-coding", label: "Z.ai Coding Plan", defaultBaseUrl: "https://api.z.ai/api/coding/paas/v4", docs: "https://docs.z.ai" },
  { tags: ["zhipu", "glm", "z.ai", "cn"], kind: "z-ai-cn", label: "Z.ai (CN)", defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4", docs: "https://open.bigmodel.cn" },
  { tags: ["vscode", "local"], kind: "vscode-lm", label: "VS Code Language Models" },
  { tags: ["generic", "custom"], kind: "openai-compatible", label: "OpenAI-compatible" },
  { tags: ["siliconflow"], kind: "siliconflow", label: "SiliconFlow", defaultBaseUrl: "https://api.siliconflow.cn/v1", docs: "https://docs.siliconflow.com" },
  { tags: ["kluster"], kind: "kluster-ai", label: "Kluster AI", defaultBaseUrl: "https://api.kluster.ai/v1", docs: "https://docs.kluster.ai" },
  { tags: ["novita"], kind: "novita", label: "Novita AI", defaultBaseUrl: "https://api.novita.ai/v1", docs: "https://docs.novita.ai" },
  { tags: ["hyperbolic"], kind: "hyperbolic", label: "Hyperbolic AI", defaultBaseUrl: "https://api.hyperbolic.xyz/v1", docs: "https://docs.hyperbolic.xyz" },
  { tags: ["nebius"], kind: "nebius", label: "Nebius Token Factory", defaultBaseUrl: "https://api.tokenfactory.nebius.com/v1", docs: "https://docs.tokenfactory.nebius.com" },
  { tags: ["sambanova"], kind: "sambanova", label: "SambaNova Cloud", defaultBaseUrl: "https://api.sambanova.ai/v1", docs: "https://docs.sambanova.ai" },
  { tags: ["baseten"], kind: "baseten", label: "Baseten (Model APIs)", defaultBaseUrl: "https://inference.baseten.co/v1", docs: "https://docs.baseten.co" },
  { tags: ["lambda"], kind: "lambda-ai", label: "Lambda AI", defaultBaseUrl: "https://api.lambda.ai/v1", docs: "https://docs.lambda.ai" },
  { tags: ["lepton"], kind: "lepton", label: "Lepton AI", defaultBaseUrl: "https://api.lepton.ai/api/v1", docs: "https://docs.lepton.ai" },
  { tags: ["upstage"], kind: "upstage", label: "Upstage AI", defaultBaseUrl: "https://api.upstage.ai/v1", docs: "https://docs.upstage.ai" },
  { tags: ["jina"], kind: "jina", label: "Jina AI", defaultBaseUrl: "https://api.jina.ai/v1", docs: "https://jina.ai/docs" },
  { tags: ["voyage"], kind: "voyage", label: "Voyage AI", defaultBaseUrl: "https://api.voyageai.com/v1", docs: "https://docs.voyageai.com" },
  { tags: ["huggingface", "hf"], kind: "huggingface", label: "Hugging Face Inference", defaultBaseUrl: "https://router.huggingface.co/v1", docs: "https://huggingface.co/docs/inference-providers" },
  { tags: ["github"], kind: "github-models", label: "GitHub Models", defaultBaseUrl: "https://models.inference.ai.azure.com", docs: "https://docs.github.com/en/github-models" },
  { tags: ["nvidia", "nim"], kind: "nvidia", label: "NVIDIA API Catalog", defaultBaseUrl: "https://integrate.api.nvidia.com/v1", docs: "https://docs.nvidia.com/nim" },
  { tags: ["scaleway"], kind: "scaleway", label: "Scaleway Generative APIs", defaultBaseUrl: "https://api.scaleway.ai/v1", docs: "https://www.scaleway.com/en/docs/ai-data/generative-api" },
  { tags: ["telnyx"], kind: "telnyx", label: "Telnyx Inference", defaultBaseUrl: "https://api.telnyx.com/v2/ai", docs: "https://developers.telnyx.com/docs/api/v2/ai" },
  { tags: ["azure"], kind: "azure-openai", label: "Azure OpenAI", defaultBaseUrl: "https://{resourceName}.openai.azure.com/openai/v1", docs: "https://learn.microsoft.com/azure/ai-services/openai" },
  { tags: ["azure", "foundry"], kind: "azure-foundry", label: "Azure AI Foundry", defaultBaseUrl: "https://{resourceName}.services.ai.azure.com/openai/v1", docs: "https://learn.microsoft.com/azure/foundry" },
  { tags: ["bedrock", "aws"], kind: "aws-bedrock", label: "Amazon Bedrock", defaultBaseUrl: "https://bedrock-runtime.{region}.amazonaws.com/openai/v1", docs: "https://docs.aws.amazon.com/bedrock" },
  { tags: ["bedrock", "mantle", "aws"], kind: "aws-bedrock-mantle", label: "Amazon Bedrock (Mantle)", defaultBaseUrl: "https://bedrock-mantle.{region}.api.aws/openai/v1", docs: "https://docs.aws.amazon.com/bedrock" },
  { tags: ["vertex", "gcp"], kind: "gcp-vertex", label: "Google Cloud Vertex AI", defaultBaseUrl: "https://{region}-aiplatform.googleapis.com/v1beta1/projects/{project_id}/locations/{location}/endpoints/openapi", docs: "https://cloud.google.com/vertex-ai" },
  { tags: ["watsonx", "ibm"], kind: "ibm-watsonx", label: "IBM watsonx.ai", defaultBaseUrl: "https://{region}.ml.cloud.ibm.com/ml/v1", docs: "https://cloud.ibm.com/docs/watsonx" },
  { tags: ["databricks"], kind: "databricks", label: "Databricks Model Serving", defaultBaseUrl: "https://{workspace-url}/serving-endpoints", docs: "https://docs.databricks.com/machine-learning/model-serving" },
  { tags: ["snowflake"], kind: "snowflake-cortex", label: "Snowflake Cortex", defaultBaseUrl: "https://{account-identifier}.snowflakecomputing.com/api/v2/cortex/v1", docs: "https://docs.snowflake.com" },
  { tags: ["cloudflare"], kind: "cloudflare-workers-ai", label: "Cloudflare Workers AI", defaultBaseUrl: "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1", docs: "https://developers.cloudflare.com/workers-ai" },
  { tags: ["volcengine", "doubao", "ark"], kind: "volcengine", label: "Volcengine (Doubao / Ark)", defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3", docs: "https://www.volcengine.com/docs" },
  { tags: ["byteplus", "modelark"], kind: "byteplus", label: "Byteplus ModelArk", defaultBaseUrl: "https://ark.ap-southeast-bytepluses.com/api/v3", docs: "https://docs.byteplus.com" },
  { tags: ["tencent", "hunyuan"], kind: "tencent-cloud", label: "Tencent Cloud Hunyuan", defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1", docs: "https://cloud.tencent.com/document/product/1729" },
  { tags: ["tencent", "tokenhub"], kind: "tencent-tokenhub", label: "Tencent TokenHub", defaultBaseUrl: "https://tokenhub.tencentmaas.com/v1", docs: "https://docs.openclaw.ai/providers/tencent" },
  { tags: ["tencent", "tokenhub", "intl"], kind: "tencent-tokenhub-intl", label: "Tencent TokenHub International", defaultBaseUrl: "https://tokenhub-intl.tencentcloudmaas.com/v1", docs: "https://docs.openclaw.ai/providers/tencent" },
  { tags: ["baidu", "qianfan", "ernie"], kind: "baidu-qianfan", label: "Baidu Qianfan", defaultBaseUrl: "https://qianfan.baidubce.com/v2", docs: "https://cloud.baidu.com/doc/WENXINWORKSHOP" },
  { tags: ["baidu", "qianfan"], kind: "baidu-qianfan-ai", label: "Baidu Qianfan AI", defaultBaseUrl: "https://api.baiduqianfan.ai/v1", docs: "https://www.comet.com/docs/opik/integrations/qianfan" },
  { tags: ["aiml"], kind: "aiml-api", label: "AI/ML API", defaultBaseUrl: "https://api.aimlapi.com/v1", docs: "https://docs.aimlapi.com" },
  { tags: ["stepfun"], kind: "stepfun", label: "StepFun", defaultBaseUrl: "https://api.stepfun.com/v1", docs: "https://platform.stepfun.com/docs" },
  { tags: ["baichuan"], kind: "baichuan", label: "Baichuan AI", defaultBaseUrl: "https://api.baichuan-ai.com/v1", docs: "https://platform.baichuan-ai.com" },
  { tags: ["01.ai", "yi"], kind: "zeroone", label: "01.AI (Yi)", defaultBaseUrl: "https://api.01.ai/v1", docs: "https://platform.01.ai" },
  { tags: ["sensenova"], kind: "sensenova", label: "SenseNova", defaultBaseUrl: "https://api.sensenova.cn/v1", docs: "https://platform.sensenova.cn" },
  { tags: ["ai21"], kind: "ai21", label: "AI21 Labs", defaultBaseUrl: "https://api.ai21.com/studio/v1", docs: "https://docs.ai21.com" },
  { tags: ["writer"], kind: "writer", label: "Writer API", defaultBaseUrl: "https://api.writer.com/v1", docs: "https://dev.writer.com" },
  { tags: ["llama-api"], kind: "llama-api", label: "Llama API", defaultBaseUrl: "https://api.llama-api.com", docs: "https://www.llama-api.com/docs" },
  { tags: ["venice"], kind: "venice", label: "Venice.ai", defaultBaseUrl: "https://api.venice.ai/api/v1", docs: "https://docs.venice.ai" },
  { tags: ["clarifai"], kind: "clarifai", label: "Clarifai", defaultBaseUrl: "https://api.clarifai.com/v2/ext/openai/v1", docs: "https://docs.clarifai.com" },
  { tags: ["sarvam"], kind: "sarvam", label: "Sarvam AI", defaultBaseUrl: "https://api.sarvam.ai", docs: "https://docs.sarvam.ai" },
  { tags: ["ovhcloud"], kind: "ovhcloud", label: "OVHcloud AI Endpoints", defaultBaseUrl: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1", docs: "https://docs.ovhcloud.com" },
  { tags: ["llmhub", "t-systems"], kind: "llmhub", label: "T-Systems LLMhub", defaultBaseUrl: "https://llm-server.llmhub.t-systems.net/v2", docs: "https://docs.llmhub.t-systems.net" },
  { tags: ["friendli"], kind: "friendli", label: "FriendliAI", defaultBaseUrl: "https://api.friendli.ai/v1", docs: "https://docs.friendli.ai" },
  { tags: ["predibase"], kind: "predibase", label: "Predibase", defaultBaseUrl: "https://serving.app.predibase.com", docs: "https://docs.predibase.com" },
  { tags: ["morph"], kind: "morph", label: "Morph Chat", defaultBaseUrl: "https://api.morph.chat/v1", docs: "https://docs.morph.chat" },
  { tags: ["fal"], kind: "fal", label: "Fal.ai", defaultBaseUrl: "https://queue.fal.run", docs: "https://fal.ai/docs" },
  { tags: ["bfl", "black forest labs", "flux"], kind: "bfl", label: "Black Forest Labs", defaultBaseUrl: "https://api.bfl.ai/v1", docs: "https://docs.bfl.ai" },
  { tags: ["modelslab"], kind: "modelslab", label: "ModelsLab", defaultBaseUrl: "https://modelslab.com/api/v1", docs: "https://modelslab.com/docs" },
  { tags: ["apiyi"], kind: "apiyi", label: "APIYI", defaultBaseUrl: "https://api.apiyi.com/v1", docs: "https://docs.apiyi.com" },
  { tags: ["laozhang"], kind: "laozhang", label: "LaoZhang API", defaultBaseUrl: "https://api.laozhang.ai/v1", docs: "https://docs.laozhang.ai" },
  { tags: ["featherless"], kind: "featherless", label: "Featherless AI", defaultBaseUrl: "https://api.featherless.ai/v1", docs: "https://docs.featherless.ai" },
  { tags: ["decart"], kind: "decart", label: "Decart AI", defaultBaseUrl: "https://api.decart.ai/v1", docs: "https://docs.decart.ai" },
  { tags: ["eden"], kind: "edenai", label: "Eden AI", defaultBaseUrl: "https://api.edenai.run/v2", docs: "https://docs.edenai.co" },
  { tags: ["orq"], kind: "orq", label: "Orq.ai", defaultBaseUrl: "https://api.orq.ai/v1", docs: "https://docs.orq.ai" },
  { tags: ["martian"], kind: "martian", label: "Martian", defaultBaseUrl: "https://api.withmartian.com/v1", docs: "https://docs.withmartian.com" },
  { tags: ["requesty"], kind: "requesty", label: "Requesty", defaultBaseUrl: "https://api.requesty.ai/v1", docs: "https://docs.requesty.ai" },
  { tags: ["helicone"], kind: "helicone", label: "Helicone", defaultBaseUrl: "https://gateway.helicone.ai/v1", docs: "https://docs.helicone.ai" },
  { tags: ["portkey"], kind: "portkey", label: "Portkey", defaultBaseUrl: "https://api.portkey.ai/v1", docs: "https://docs.portkey.ai" },
  { tags: ["local", "lm studio"], kind: "lm-studio", label: "LM Studio (Local)", defaultBaseUrl: "http://localhost:1234/v1", docs: "https://lmstudio.ai" },
  { tags: ["local"], kind: "localai", label: "LocalAI", defaultBaseUrl: "http://localhost:8080/v1", docs: "https://localai.io" },
  { tags: ["local", "jan"], kind: "jan", label: "Jan (Local)", defaultBaseUrl: "http://localhost:1337/v1", docs: "https://jan.ai" },
  { tags: ["local"], kind: "gpt4all", label: "GPT4All", defaultBaseUrl: "http://localhost:4891/v1", docs: "https://gpt4all.io" },
  { tags: ["local"], kind: "koboldcpp", label: "KoboldCPP", defaultBaseUrl: "http://localhost:5001/v1", docs: "https://github.com/LostRuins/koboldcpp" },
  { tags: ["local"], kind: "llamafile", label: "Llamafile", defaultBaseUrl: "http://localhost:8080/v1", docs: "https://github.com/Mozilla-Ocho/llamafile" },
  { tags: ["local"], kind: "llama-cpp", label: "llama.cpp / llama-server", defaultBaseUrl: "http://localhost:8080/v1", docs: "https://github.com/ggerganov/llama.cpp" },
  { tags: ["local"], kind: "vllm", label: "vLLM", defaultBaseUrl: "http://localhost:8000/v1", docs: "https://docs.vllm.ai" },
  { tags: ["local"], kind: "sglang", label: "SGLang", defaultBaseUrl: "http://localhost:30000/v1", docs: "https://github.com/sgl-project/sglang" },
  { tags: ["local"], kind: "tgi", label: "Text Generation Inference (TGI)", defaultBaseUrl: "http://localhost:8080/v1", docs: "https://huggingface.co/docs/text-generation-inference" },
  { tags: ["local"], kind: "aphrodite", label: "Aphrodite Engine", defaultBaseUrl: "http://localhost:2242/v1", docs: "https://github.com/Alpindale/aphrodite-engine" },
  { tags: ["local"], kind: "xinference", label: "Xinference", defaultBaseUrl: "http://localhost:9997/v1", docs: "https://github.com/xorbitsai/inference" },
  { tags: ["local"], kind: "tabby", label: "Tabby Coding Assistant", defaultBaseUrl: "http://localhost:8080/v1", docs: "https://tabby.tabbyml.com" },
  { tags: ["proxy"], kind: "one-api", label: "One API", defaultBaseUrl: "http://localhost:3000/v1", docs: "https://github.com/songquanpeng/one-api" },
  { tags: ["proxy"], kind: "new-api", label: "New API", defaultBaseUrl: "http://localhost:3000/v1", docs: "https://github.com/Calcium-DEC/new-api" },
  { tags: ["proxy"], kind: "any-llm", label: "Any-LLM Control Plane", defaultBaseUrl: "https://api.any-llm.com/v1", docs: "https://blog.mozilla.ai/run-openai-claude-mistral-llamafile-and-more-from-one-interface-now-in-go/" },
  { tags: ["wavespeed"], kind: "wavespeed", label: "WaveSpeed LLM", defaultBaseUrl: "https://api.wavespeed.ai/v1", docs: "https://wavespeed.ai/docs" },
  { tags: ["braintrust"], kind: "braintrust", label: "Braintrust", defaultBaseUrl: "https://api.braintrust.dev/v1", docs: "https://www.braintrust.dev" },
  { tags: ["aibadgr"], kind: "aibadgr", label: "AI Badgr", defaultBaseUrl: "https://aibadgr.com/api/v1", docs: "https://aibadgr.com/docs" },
  { tags: ["replicate"], kind: "replicate", label: "Replicate", defaultBaseUrl: "https://api.replicate.com/v1", docs: "https://replicate.com/docs" },
  { tags: ["chutes"], kind: "chutes", label: "Chutes AI", defaultBaseUrl: "https://api.chutes.ai/v1", docs: "https://chutes.ai" },
  { tags: ["anyscale"], kind: "anyscale", label: "Anyscale Endpoints", defaultBaseUrl: "https://api.endpoints.anyscale.com/v1", docs: "https://docs.anyscale.com" },
  { tags: ["comet"], kind: "comet-api", label: "Comet API", defaultBaseUrl: "https://api.comet.com/v1", docs: "https://comet.com" },
  { tags: ["apexit", "apertis"], kind: "apexit", label: "Apertis AI", defaultBaseUrl: "https://api.apertis.ai/v1", docs: "https://docs.apertis.ai" },
  { tags: ["llamagate"], kind: "llamagate", label: "LlamaGate", defaultBaseUrl: "https://api.llamagate.com/v1", docs: "https://llamagate.com" },
  { tags: ["nanogpt"], kind: "nanogpt", label: "NanoGPT", defaultBaseUrl: "https://nano-gpt.com/api/v1", docs: "https://nano-gpt.com" },
  { tags: ["nlp-cloud"], kind: "nlp-cloud", label: "NLP Cloud", defaultBaseUrl: "https://api.nlpcloud.com/v1", docs: "https://docs.nlpcloud.com" },
  { tags: ["baseten"], kind: "baseten-predict", label: "Baseten Dedicated Endpoints", defaultBaseUrl: "https://model-{model_id}.api.baseten.co", docs: "https://docs.baseten.co" },
  { tags: ["vercel", "v0"], kind: "v0", label: "Vercel v0", defaultBaseUrl: "https://api.v0.dev/v1", docs: "https://v0.dev" },
  { tags: ["spheron"], kind: "spheron", label: "Spheron Network", defaultBaseUrl: "https://api.spheron.network/v1", docs: "https://docs.spheron.network" },
  { tags: ["unify"], kind: "unify-ai", label: "Unify AI", defaultBaseUrl: "https://api.unify.ai/v1", docs: "https://unify.ai/docs" },
  { tags: ["zenmux"], kind: "zenmux", label: "ZenMux", defaultBaseUrl: "https://api.zenmux.com/v1", docs: "https://docs.zenmux.com" },
  { tags: ["bifrost"], kind: "bifrost", label: "Bifrost AI", defaultBaseUrl: "https://api.bifrost.ai/v1", docs: "https://docs.bifrost.ai" },
  { tags: ["nscale", "eu"], kind: "nscale", label: "Nscale", defaultBaseUrl: "https://api.nscale.com/v1", docs: "https://docs.nscale.com" },
  { tags: ["publicai"], kind: "publicai", label: "PublicAI", defaultBaseUrl: "https://api.publicai.com/v1", docs: "https://publicai.com" },
  { tags: ["galadriel"], kind: "galadriel", label: "Galadriel", defaultBaseUrl: "https://api.galadriel.com/v1", docs: "https://docs.galadriel.com" },
  { tags: ["gmi"], kind: "gmi-cloud", label: "GMI Cloud", defaultBaseUrl: "https://api.gmicloud.ai/v1", docs: "https://www.gmicloud.ai" },
  { tags: ["shareai"], kind: "shareai", label: "ShareAI", defaultBaseUrl: "https://api.shareai.now/v1", docs: "https://shareai.now" },
  { tags: ["qwen", "ali", "dashscope"], kind: "dashscope", label: "Alibaba DashScope (Qwen)", defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1", docs: "https://dashscope.aliyun.com" },
  { tags: ["oci", "oracle"], kind: "oracle-oci", label: "Oracle Cloud Infrastructure GenAI", defaultBaseUrl: "https://generativeai.oci.oraclecloud.com", docs: "https://docs.oracle.com/en-us/iaas/Content/generative-ai/home.htm" },
  { tags: ["aleph-alpha"], kind: "aleph-alpha", label: "Aleph Alpha", defaultBaseUrl: "https://api.aleph-alpha.com/v1", docs: "https://docs.aleph-alpha.com" },
  { tags: ["bytez"], kind: "bytez", label: "Bytez", defaultBaseUrl: "https://api.bytez.com/v1", docs: "https://bytez.com" },
  { tags: ["compactifai"], kind: "compactifai", label: "CompactifAI", defaultBaseUrl: "https://api.compactif.ai/v1", docs: "https://docs.compactif.ai" },
  { tags: ["empirio"], kind: "empiriolabs", label: "EmpirioLabs AI", defaultBaseUrl: "https://api.empiriolabs.ai/v1", docs: "https://empiriolabs.ai" },
  { tags: ["inception"], kind: "inception", label: "Inception AI", defaultBaseUrl: "https://api.inception.ai/v1", docs: "https://inception.ai" },
  { tags: ["lemonade"], kind: "lemonade", label: "Lemonade Server", defaultBaseUrl: "http://localhost:8080/v1", docs: "https://lemonade.ai" },
  { tags: ["manus"], kind: "manus", label: "Manus AI", defaultBaseUrl: "https://api.manus.ai/v1", docs: "https://manus.ai" },
  { tags: ["poe"], kind: "poe", label: "Poe", defaultBaseUrl: "https://api.poe.com/v1", docs: "https://poe.com" },
  { tags: ["recraft"], kind: "recraft", label: "Recraft", defaultBaseUrl: "https://api.recraft.ai/v1", docs: "https://recraft.ai" },
  { tags: ["runway"], kind: "runwayml", label: "RunwayML", defaultBaseUrl: "https://api.runwayml.com/v1", docs: "https://runwayml.com" },
  { tags: ["stability"], kind: "stability-ai", label: "Stability AI", defaultBaseUrl: "https://api.stability.ai/v1", docs: "https://stability.ai" },
  { tags: ["topaz"], kind: "topaz", label: "Topaz AI", defaultBaseUrl: "https://api.topaz.ai/v1", docs: "https://topaz.ai" },
  { tags: ["wandb", "weave"], kind: "wandb-inference", label: "Weights & Biases Inference", defaultBaseUrl: "https://api.wandb.ai/v1", docs: "https://weave-docs.wandb.ai" },
  { tags: ["xiaomi", "mimo"], kind: "xiaomi-mimo", label: "Xiaomi MiMo", defaultBaseUrl: "https://platform.xiaomimimo.com/api/v1", docs: "https://platform.xiaomimimo.com" },
  { tags: ["petals"], kind: "petals", label: "Petals", defaultBaseUrl: "http://localhost:8080", docs: "https://github.com/bigscience-workshop/petals" },
  { tags: ["triton"], kind: "triton-inference", label: "Triton Inference Server", defaultBaseUrl: "http://localhost:8000/v1", docs: "https://docs.nvidia.com/deeplearning/triton-inference-server" },
  { tags: ["tensormesh"], kind: "tensormesh", label: "TensorMesh", defaultBaseUrl: "https://api.tensormesh.ai/v1", docs: "https://tensormesh.ai" },
  { tags: ["synthetic"], kind: "synthetic", label: "Synthetic", defaultBaseUrl: "https://api.synthetic.ai/v1", docs: "https://synthetic.ai" },
  { tags: ["datarobot"], kind: "datarobot", label: "DataRobot", defaultBaseUrl: "https://app.datarobot.com/api/v1", docs: "https://docs.datarobot.com" },
  { tags: ["gradient"], kind: "gradientai", label: "Gradient AI", defaultBaseUrl: "https://api.gradient.ai/v1", docs: "https://gradient.ai" },
  { tags: ["heroku"], kind: "heroku", label: "Heroku AI", defaultBaseUrl: "https://api.heroku.com/ai/v1", docs: "https://devcenter.heroku.com" },
  { tags: ["near"], kind: "near-ai", label: "NEAR AI Cloud", defaultBaseUrl: "https://api.near.ai/v1", docs: "https://near.ai" },
  { tags: ["litellm", "proxy"], kind: "litellm-proxy", label: "LiteLLM Proxy", defaultBaseUrl: "http://localhost:4000/v1", docs: "https://docs.litellm.ai" },
  { tags: ["portkey", "gateway"], kind: "portkey-gateway", label: "Portkey Gateway", defaultBaseUrl: "https://api.portkey.ai/v1", docs: "https://portkey.ai" },
  { tags: ["braintrust", "gateway"], kind: "braintrust-gateway", label: "Braintrust Gateway", defaultBaseUrl: "https://api.braintrust.dev/v1", docs: "https://www.braintrust.dev" },
  { tags: ["vercel", "gateway"], kind: "vercel-ai-gateway", label: "Vercel AI Gateway", defaultBaseUrl: "https://ai-gateway.vercel.sh/v1", docs: "https://vercel.com/docs/ai-gateway" },
  { tags: ["qwen", "tongyi"], kind: "tongyi", label: "Alibaba Tongyi (Qwen)", defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1", docs: "https://dashscope.aliyun.com" },
  { tags: ["deepgram"], kind: "deepgram", label: "Deepgram (Text)", defaultBaseUrl: "https://api.deepgram.com/v1", docs: "https://developers.deepgram.com" },
  { tags: ["elevenlabs", "text"], kind: "elevenlabs", label: "ElevenLabs (Text)", defaultBaseUrl: "https://api.elevenlabs.io/v1", docs: "https://elevenlabs.io/docs" },
=======
  { tags: ["gpt", "chatgpt"], kind: "openai", label: "OpenAI", defaultBaseUrl: "https://api.openai.com/v1" },
  { tags: ["router", "multi-model"], kind: "openrouter", label: "OpenRouter", defaultBaseUrl: "https://openrouter.ai/api/v1" },
  { tags: ["claude", "sonnet", "opus", "fable"], kind: "anthropic", label: "Anthropic", defaultBaseUrl: "https://api.anthropic.com/v1" },
  { tags: ["gemini", "gemma", "bard", "palm", "deepmind"], kind: "google", label: "Google AI", defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta/openai" },
  { tags: ["groq", "fast inference"], kind: "groq", label: "Groq", defaultBaseUrl: "https://api.groq.com/openai/v1" },
  { tags: ["mistral", "mixtral", "codestral", "devstral"], kind: "mistral", label: "Mistral", defaultBaseUrl: "https://api.mistral.ai/v1" },
  { tags: ["deepseek", "v4"], kind: "deepseek", label: "DeepSeek", defaultBaseUrl: "https://api.deepseek.com/v1" },
  { tags: ["grok", "xai"], kind: "xai", label: "xAI", defaultBaseUrl: "https://api.x.ai/v1" },
  { tags: ["command", "aya"], kind: "cohere", label: "Cohere", defaultBaseUrl: "https://api.cohere.ai/compatibility/v1" },
  { tags: ["fireworks"], kind: "fireworks", label: "Fireworks AI", defaultBaseUrl: "https://api.fireworks.ai/inference/v1" },
  { tags: ["together"], kind: "together", label: "Together AI", defaultBaseUrl: "https://api.together.xyz/v1" },
  { tags: ["perplexity", "sonar"], kind: "perplexity", label: "Perplexity", defaultBaseUrl: "https://api.perplexity.ai" },
  { tags: ["deepinfra"], kind: "deepinfra", label: "DeepInfra", defaultBaseUrl: "https://api.deepinfra.com/v1/openai" },
  { tags: ["cerebras"], kind: "cerebras", label: "Cerebras", defaultBaseUrl: "https://api.cerebras.ai/v1" },
  { tags: ["local"], kind: "ollama", label: "Ollama", defaultBaseUrl: "http://127.0.0.1:11434" },
  { tags: ["minimax"], kind: "minimax", label: "MiniMax", defaultBaseUrl: "https://api.minimax.io/v1" },
  { tags: ["minimax", "cn"], kind: "minimax-cn", label: "MiniMax (CN)", defaultBaseUrl: "https://api.minimaxi.com/v1" },
  { tags: ["kimi", "moonshot"], kind: "kimi", label: "Kimi", defaultBaseUrl: "https://api.moonshot.ai/v1" },
  { tags: ["kimi", "moonshot", "cn"], kind: "kimi-cn", label: "Kimi (CN)", defaultBaseUrl: "https://api.moonshot.cn/v1" },
  { tags: ["zhipu", "glm", "z.ai"], kind: "z-ai", label: "Z.ai", defaultBaseUrl: "https://api.z.ai/api/paas/v4" },
  { tags: ["zhipu", "glm", "z.ai", "coding plan"], kind: "z-ai-coding", label: "Z.ai Coding Plan", defaultBaseUrl: "https://api.z.ai/api/coding/paas/v4" },
  { tags: ["zhipu", "glm", "z.ai", "cn"], kind: "z-ai-cn", label: "Z.ai (CN)", defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4" },
  { tags: ["vscode", "local"], kind: "vscode-lm", label: "VS Code Language Models" },
  { tags: ["generic", "custom"], kind: "openai-compatible", label: "OpenAI-compatible" },
  { tags: ["siliconflow"], kind: "siliconflow", label: "SiliconFlow", defaultBaseUrl: "https://api.siliconflow.cn/v1" },
  { tags: ["kluster"], kind: "kluster-ai", label: "Kluster AI", defaultBaseUrl: "https://api.kluster.ai/v1" },
  { tags: ["novita"], kind: "novita", label: "Novita AI", defaultBaseUrl: "https://api.novita.ai/v1" },
  { tags: ["hyperbolic"], kind: "hyperbolic", label: "Hyperbolic AI", defaultBaseUrl: "https://api.hyperbolic.xyz/v1" },
  { tags: ["nebius"], kind: "nebius", label: "Nebius Token Factory", defaultBaseUrl: "https://api.tokenfactory.nebius.com/v1" },
  { tags: ["sambanova"], kind: "sambanova", label: "SambaNova Cloud", defaultBaseUrl: "https://api.sambanova.ai/v1" },
  { tags: ["baseten"], kind: "baseten", label: "Baseten (Model APIs)", defaultBaseUrl: "https://inference.baseten.co/v1" },
  { tags: ["lambda"], kind: "lambda-ai", label: "Lambda AI", defaultBaseUrl: "https://api.lambda.ai/v1" },
  { tags: ["lepton"], kind: "lepton", label: "Lepton AI", defaultBaseUrl: "https://api.lepton.ai/api/v1" },
  { tags: ["upstage"], kind: "upstage", label: "Upstage AI", defaultBaseUrl: "https://api.upstage.ai/v1" },
  { tags: ["jina"], kind: "jina", label: "Jina AI", defaultBaseUrl: "https://api.jina.ai/v1" },
  { tags: ["voyage"], kind: "voyage", label: "Voyage AI", defaultBaseUrl: "https://api.voyageai.com/v1" },
  { tags: ["huggingface", "hf"], kind: "huggingface", label: "Hugging Face Inference", defaultBaseUrl: "https://router.huggingface.co/v1" },
  { tags: ["github"], kind: "github-models", label: "GitHub Models", defaultBaseUrl: "https://models.inference.ai.azure.com" },
  { tags: ["nvidia", "nim"], kind: "nvidia", label: "NVIDIA API Catalog", defaultBaseUrl: "https://integrate.api.nvidia.com/v1" },
  { tags: ["scaleway"], kind: "scaleway", label: "Scaleway Generative APIs", defaultBaseUrl: "https://api.scaleway.ai/v1" },
  { tags: ["telnyx"], kind: "telnyx", label: "Telnyx Inference", defaultBaseUrl: "https://api.telnyx.com/v2/ai" },
  { tags: ["azure"], kind: "azure-openai", label: "Azure OpenAI", defaultBaseUrl: "https://{resourceName}.openai.azure.com/openai/v1" },
  { tags: ["azure", "foundry"], kind: "azure-foundry", label: "Azure AI Foundry", defaultBaseUrl: "https://{resourceName}.services.ai.azure.com/openai/v1" },
  { tags: ["bedrock", "aws"], kind: "aws-bedrock", label: "Amazon Bedrock", defaultBaseUrl: "https://bedrock-runtime.{region}.amazonaws.com/openai/v1" },
  { tags: ["bedrock", "mantle", "aws"], kind: "aws-bedrock-mantle", label: "Amazon Bedrock (Mantle)", defaultBaseUrl: "https://bedrock-mantle.{region}.api.aws/openai/v1" },
  { tags: ["vertex", "gcp"], kind: "gcp-vertex", label: "Google Cloud Vertex AI", defaultBaseUrl: "https://{region}-aiplatform.googleapis.com/v1beta1/projects/{project_id}/locations/{location}/endpoints/openapi" },
  { tags: ["watsonx", "ibm"], kind: "ibm-watsonx", label: "IBM watsonx.ai", defaultBaseUrl: "https://{region}.ml.cloud.ibm.com/ml/v1" },
  { tags: ["databricks"], kind: "databricks", label: "Databricks Model Serving", defaultBaseUrl: "https://{workspace-url}/serving-endpoints" },
  { tags: ["snowflake"], kind: "snowflake-cortex", label: "Snowflake Cortex", defaultBaseUrl: "https://{account-identifier}.snowflakecomputing.com/api/v2/cortex/v1" },
  { tags: ["cloudflare"], kind: "cloudflare-workers-ai", label: "Cloudflare Workers AI", defaultBaseUrl: "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1" },
  { tags: ["volcengine", "doubao", "ark"], kind: "volcengine", label: "Volcengine (Doubao / Ark)", defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3" },
  { tags: ["byteplus", "modelark"], kind: "byteplus", label: "Byteplus ModelArk", defaultBaseUrl: "https://ark.ap-southeast-bytepluses.com/api/v3" },
  { tags: ["tencent", "hunyuan"], kind: "tencent-cloud", label: "Tencent Cloud Hunyuan", defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1" },
  { tags: ["tencent", "tokenhub"], kind: "tencent-tokenhub", label: "Tencent TokenHub", defaultBaseUrl: "https://tokenhub.tencentmaas.com/v1" },
  { tags: ["tencent", "tokenhub", "intl"], kind: "tencent-tokenhub-intl", label: "Tencent TokenHub International", defaultBaseUrl: "https://tokenhub-intl.tencentcloudmaas.com/v1" },
  { tags: ["baidu", "qianfan", "ernie"], kind: "baidu-qianfan", label: "Baidu Qianfan", defaultBaseUrl: "https://qianfan.baidubce.com/v2" },
  { tags: ["baidu", "qianfan"], kind: "baidu-qianfan-ai", label: "Baidu Qianfan AI", defaultBaseUrl: "https://api.baiduqianfan.ai/v1" },
  { tags: ["aiml"], kind: "aiml-api", label: "AI/ML API", defaultBaseUrl: "https://api.aimlapi.com/v1" },
  { tags: ["stepfun"], kind: "stepfun", label: "StepFun", defaultBaseUrl: "https://api.stepfun.com/v1" },
  { tags: ["baichuan"], kind: "baichuan", label: "Baichuan AI", defaultBaseUrl: "https://api.baichuan-ai.com/v1" },
  { tags: ["01.ai", "yi"], kind: "zeroone", label: "01.AI (Yi)", defaultBaseUrl: "https://api.01.ai/v1" },
  { tags: ["sensenova"], kind: "sensenova", label: "SenseNova", defaultBaseUrl: "https://api.sensenova.cn/v1" },
  { tags: ["ai21"], kind: "ai21", label: "AI21 Labs", defaultBaseUrl: "https://api.ai21.com/studio/v1" },
  { tags: ["writer"], kind: "writer", label: "Writer API", defaultBaseUrl: "https://api.writer.com/v1" },
  { tags: ["llama-api"], kind: "llama-api", label: "Llama API", defaultBaseUrl: "https://api.llama-api.com" },
  { tags: ["venice"], kind: "venice", label: "Venice.ai", defaultBaseUrl: "https://api.venice.ai/api/v1" },
  { tags: ["clarifai"], kind: "clarifai", label: "Clarifai", defaultBaseUrl: "https://api.clarifai.com/v2/ext/openai/v1" },
  { tags: ["sarvam"], kind: "sarvam", label: "Sarvam AI", defaultBaseUrl: "https://api.sarvam.ai" },
  { tags: ["ovhcloud"], kind: "ovhcloud", label: "OVHcloud AI Endpoints", defaultBaseUrl: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1" },
  { tags: ["llmhub", "t-systems"], kind: "llmhub", label: "T-Systems LLMhub", defaultBaseUrl: "https://llm-server.llmhub.t-systems.net/v2" },
  { tags: ["friendli"], kind: "friendli", label: "FriendliAI", defaultBaseUrl: "https://api.friendli.ai/v1" },
  { tags: ["predibase"], kind: "predibase", label: "Predibase", defaultBaseUrl: "https://serving.app.predibase.com" },
  { tags: ["morph"], kind: "morph", label: "Morph Chat", defaultBaseUrl: "https://api.morph.chat/v1" },
  { tags: ["fal"], kind: "fal", label: "Fal.ai", defaultBaseUrl: "https://queue.fal.run" },
  { tags: ["bfl", "black forest labs", "flux"], kind: "bfl", label: "Black Forest Labs", defaultBaseUrl: "https://api.bfl.ai/v1" },
  { tags: ["modelslab"], kind: "modelslab", label: "ModelsLab", defaultBaseUrl: "https://modelslab.com/api/v1" },
  { tags: ["apiyi"], kind: "apiyi", label: "APIYI", defaultBaseUrl: "https://api.apiyi.com/v1" },
  { tags: ["laozhang"], kind: "laozhang", label: "LaoZhang API", defaultBaseUrl: "https://api.laozhang.ai/v1" },
  { tags: ["featherless"], kind: "featherless", label: "Featherless AI", defaultBaseUrl: "https://api.featherless.ai/v1" },
  { tags: ["decart"], kind: "decart", label: "Decart AI", defaultBaseUrl: "https://api.decart.ai/v1" },
  { tags: ["eden"], kind: "edenai", label: "Eden AI", defaultBaseUrl: "https://api.edenai.run/v2" },
  { tags: ["orq"], kind: "orq", label: "Orq.ai", defaultBaseUrl: "https://api.orq.ai/v1" },
  { tags: ["martian"], kind: "martian", label: "Martian", defaultBaseUrl: "https://api.withmartian.com/v1" },
  { tags: ["requesty"], kind: "requesty", label: "Requesty", defaultBaseUrl: "https://api.requesty.ai/v1" },
  { tags: ["helicone"], kind: "helicone", label: "Helicone", defaultBaseUrl: "https://gateway.helicone.ai/v1" },
  { tags: ["portkey"], kind: "portkey", label: "Portkey", defaultBaseUrl: "https://api.portkey.ai/v1" },
  { tags: ["local", "lm studio"], kind: "lm-studio", label: "LM Studio (Local)", defaultBaseUrl: "http://localhost:1234/v1" },
  { tags: ["local"], kind: "localai", label: "LocalAI", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["local", "jan"], kind: "jan", label: "Jan (Local)", defaultBaseUrl: "http://localhost:1337/v1" },
  { tags: ["local"], kind: "gpt4all", label: "GPT4All", defaultBaseUrl: "http://localhost:4891/v1" },
  { tags: ["local"], kind: "koboldcpp", label: "KoboldCPP", defaultBaseUrl: "http://localhost:5001/v1" },
  { tags: ["local"], kind: "llamafile", label: "Llamafile", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["local"], kind: "llama-cpp", label: "llama.cpp / llama-server", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["local"], kind: "vllm", label: "vLLM", defaultBaseUrl: "http://localhost:8000/v1" },
  { tags: ["local"], kind: "sglang", label: "SGLang", defaultBaseUrl: "http://localhost:30000/v1" },
  { tags: ["local"], kind: "tgi", label: "Text Generation Inference (TGI)", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["local"], kind: "aphrodite", label: "Aphrodite Engine", defaultBaseUrl: "http://localhost:2242/v1" },
  { tags: ["local"], kind: "xinference", label: "Xinference", defaultBaseUrl: "http://localhost:9997/v1" },
  { tags: ["local"], kind: "tabby", label: "Tabby Coding Assistant", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["proxy"], kind: "one-api", label: "One API", defaultBaseUrl: "http://localhost:3000/v1" },
  { tags: ["proxy"], kind: "new-api", label: "New API", defaultBaseUrl: "http://localhost:3000/v1" },
  { tags: ["proxy"], kind: "any-llm", label: "Any-LLM Control Plane", defaultBaseUrl: "https://api.any-llm.com/v1" },
  { tags: ["wavespeed"], kind: "wavespeed", label: "WaveSpeed LLM", defaultBaseUrl: "https://api.wavespeed.ai/v1" },
  { tags: ["braintrust"], kind: "braintrust", label: "Braintrust", defaultBaseUrl: "https://api.braintrust.dev/v1" },
  { tags: ["aibadgr"], kind: "aibadgr", label: "AI Badgr", defaultBaseUrl: "https://aibadgr.com/api/v1" },
  { tags: ["replicate"], kind: "replicate", label: "Replicate", defaultBaseUrl: "https://api.replicate.com/v1" },
  { tags: ["chutes"], kind: "chutes", label: "Chutes AI", defaultBaseUrl: "https://api.chutes.ai/v1" },
  { tags: ["anyscale"], kind: "anyscale", label: "Anyscale Endpoints", defaultBaseUrl: "https://api.endpoints.anyscale.com/v1" },
  { tags: ["comet"], kind: "comet-api", label: "Comet API", defaultBaseUrl: "https://api.comet.com/v1" },
  { tags: ["apexit", "apertis"], kind: "apexit", label: "Apertis AI", defaultBaseUrl: "https://api.apertis.ai/v1" },
  { tags: ["llamagate"], kind: "llamagate", label: "LlamaGate", defaultBaseUrl: "https://api.llamagate.com/v1" },
  { tags: ["nanogpt"], kind: "nanogpt", label: "NanoGPT", defaultBaseUrl: "https://nano-gpt.com/api/v1" },
  { tags: ["nlp-cloud"], kind: "nlp-cloud", label: "NLP Cloud", defaultBaseUrl: "https://api.nlpcloud.com/v1" },
  { tags: ["baseten"], kind: "baseten-predict", label: "Baseten Dedicated Endpoints", defaultBaseUrl: "https://model-{model_id}.api.baseten.co" },
  { tags: ["vercel", "v0"], kind: "v0", label: "Vercel v0", defaultBaseUrl: "https://api.v0.dev/v1" },
  { tags: ["spheron"], kind: "spheron", label: "Spheron Network", defaultBaseUrl: "https://api.spheron.network/v1" },
  { tags: ["unify"], kind: "unify-ai", label: "Unify AI", defaultBaseUrl: "https://api.unify.ai/v1" },
  { tags: ["zenmux"], kind: "zenmux", label: "ZenMux", defaultBaseUrl: "https://api.zenmux.com/v1" },
  { tags: ["bifrost"], kind: "bifrost", label: "Bifrost AI", defaultBaseUrl: "https://api.bifrost.ai/v1" },
  { tags: ["nscale", "eu"], kind: "nscale", label: "Nscale", defaultBaseUrl: "https://api.nscale.com/v1" },
  { tags: ["publicai"], kind: "publicai", label: "PublicAI", defaultBaseUrl: "https://api.publicai.com/v1" },
  { tags: ["galadriel"], kind: "galadriel", label: "Galadriel", defaultBaseUrl: "https://api.galadriel.com/v1" },
  { tags: ["gmi"], kind: "gmi-cloud", label: "GMI Cloud", defaultBaseUrl: "https://api.gmicloud.ai/v1" },
  { tags: ["shareai"], kind: "shareai", label: "ShareAI", defaultBaseUrl: "https://api.shareai.now/v1" },
  { tags: ["qwen", "ali", "dashscope"], kind: "dashscope", label: "Alibaba DashScope (Qwen)", defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1" },
  { tags: ["oci", "oracle"], kind: "oracle-oci", label: "Oracle Cloud Infrastructure GenAI", defaultBaseUrl: "https://generativeai.oci.oraclecloud.com" },
  { tags: ["aleph-alpha"], kind: "aleph-alpha", label: "Aleph Alpha", defaultBaseUrl: "https://api.aleph-alpha.com/v1" },
  { tags: ["bytez"], kind: "bytez", label: "Bytez", defaultBaseUrl: "https://api.bytez.com/v1" },
  { tags: ["compactifai"], kind: "compactifai", label: "CompactifAI", defaultBaseUrl: "https://api.compactif.ai/v1" },
  { tags: ["empirio"], kind: "empiriolabs", label: "EmpirioLabs AI", defaultBaseUrl: "https://api.empiriolabs.ai/v1" },
  { tags: ["inception"], kind: "inception", label: "Inception AI", defaultBaseUrl: "https://api.inception.ai/v1" },
  { tags: ["lemonade"], kind: "lemonade", label: "Lemonade Server", defaultBaseUrl: "http://localhost:8080/v1" },
  { tags: ["manus"], kind: "manus", label: "Manus AI", defaultBaseUrl: "https://api.manus.ai/v1" },
  { tags: ["poe"], kind: "poe", label: "Poe", defaultBaseUrl: "https://api.poe.com/v1" },
  { tags: ["recraft"], kind: "recraft", label: "Recraft", defaultBaseUrl: "https://api.recraft.ai/v1" },
  { tags: ["runway"], kind: "runwayml", label: "RunwayML", defaultBaseUrl: "https://api.runwayml.com/v1" },
  { tags: ["stability"], kind: "stability-ai", label: "Stability AI", defaultBaseUrl: "https://api.stability.ai/v1" },
  { tags: ["topaz"], kind: "topaz", label: "Topaz AI", defaultBaseUrl: "https://api.topaz.ai/v1" },
  { tags: ["wandb", "weave"], kind: "wandb-inference", label: "Weights & Biases Inference", defaultBaseUrl: "https://api.wandb.ai/v1" },
  { tags: ["xiaomi", "mimo"], kind: "xiaomi-mimo", label: "Xiaomi MiMo", defaultBaseUrl: "https://platform.xiaomimimo.com/api/v1" },
  { tags: ["petals"], kind: "petals", label: "Petals", defaultBaseUrl: "http://localhost:8080" },
  { tags: ["triton"], kind: "triton-inference", label: "Triton Inference Server", defaultBaseUrl: "http://localhost:8000/v1" },
  { tags: ["tensormesh"], kind: "tensormesh", label: "TensorMesh", defaultBaseUrl: "https://api.tensormesh.ai/v1" },
  { tags: ["synthetic"], kind: "synthetic", label: "Synthetic", defaultBaseUrl: "https://api.synthetic.ai/v1" },
  { tags: ["datarobot"], kind: "datarobot", label: "DataRobot", defaultBaseUrl: "https://app.datarobot.com/api/v1" },
  { tags: ["gradient"], kind: "gradientai", label: "Gradient AI", defaultBaseUrl: "https://api.gradient.ai/v1" },
  { tags: ["heroku"], kind: "heroku", label: "Heroku AI", defaultBaseUrl: "https://api.heroku.com/ai/v1" },
  { tags: ["near"], kind: "near-ai", label: "NEAR AI Cloud", defaultBaseUrl: "https://api.near.ai/v1" },
  { tags: ["litellm", "proxy"], kind: "litellm-proxy", label: "LiteLLM Proxy", defaultBaseUrl: "http://localhost:4000/v1" },
  { tags: ["portkey", "gateway"], kind: "portkey-gateway", label: "Portkey Gateway", defaultBaseUrl: "https://api.portkey.ai/v1" },
  { tags: ["braintrust", "gateway"], kind: "braintrust-gateway", label: "Braintrust Gateway", defaultBaseUrl: "https://api.braintrust.dev/v1" },
  { tags: ["vercel", "gateway"], kind: "vercel-ai-gateway", label: "Vercel AI Gateway", defaultBaseUrl: "https://ai-gateway.vercel.sh/v1" },
  { tags: ["qwen", "tongyi"], kind: "tongyi", label: "Alibaba Tongyi (Qwen)", defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1" },
  { tags: ["deepgram"], kind: "deepgram", label: "Deepgram (Text)", defaultBaseUrl: "https://api.deepgram.com/v1" },
  { tags: ["elevenlabs", "text"], kind: "elevenlabs", label: "ElevenLabs (Text)", defaultBaseUrl: "https://api.elevenlabs.io/v1" },
>>>>>>> dev
];
export function getProviderSpec(kind: ProviderKind): ProviderSpec | undefined {
  return PROVIDERS.find((p) => p.kind === kind);
}