import type { ProviderKind } from "../protocol/protocol.js";
export interface ProviderSpec {
  kind: ProviderKind;
  label: string;
  tags: string[];
  defaultBaseUrl?: string;
}
const RAW: string[] = [
  "openai|OpenAI|api.openai.com/v1|gpt,chatgpt",
  "openai-compatible|OpenAI-compatible||generic,custom",
  "vscode-lm|VS Code Language Models||local",
  "tokenrouter|TokenRouter|api.tokenrouter.com/v1|router,multi-model",
  "zeroone|01.AI (Yi)|api.01.ai/v1|",
  "302ai|302.AI|api.302.ai/v1|",
  "abacus|Abacus|routellm.abacus.ai/v1|",
  "abliteration-ai|abliteration.ai|api.abliteration.ai/v1|",
  "aibadgr|AI Badgr|aibadgr.com/api/v1|",
  "ai-router|AI-ROUTER|api.ai-router.dev/v1|",
  "aiml-api|AI/ML API|api.aimlapi.com/v1|",
  "aiand|ai&|api.aiand.com/v1|",
  "ai21|AI21 Labs|api.ai21.com/studio/v1|",
  "aki-io|AKI.IO|aki.io/v1|",
  "aleph-alpha|Aleph Alpha|api.aleph-alpha.com/v1|",
  "alibaba|Alibaba|dashscope-intl.aliyuncs.com/compatible-mode/v1|",
  "alibaba-coding-plan|Alibaba Coding Plan|coding-intl.dashscope.aliyuncs.com/v1|",
  "alibaba-coding-plan-cn|Alibaba Coding Plan (China)|coding.dashscope.aliyuncs.com/v1|",
  "dashscope|Alibaba DashScope (Qwen)|dashscope.aliyuncs.com/compatible-mode/v1|",
  "alibaba-token-plan|Alibaba Token Plan|token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1|token-plan",
  "alibaba-token-plan-cn|Alibaba Token Plan (China)|token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1|token-plan",
  "aws-bedrock|Amazon Bedrock|bedrock-runtime.{region}.amazonaws.com/openai/v1|",
  "aws-bedrock-mantle|Amazon Bedrock (Mantle)|bedrock-mantle.{region}.api.aws/openai/v1|",
  "ambient|Ambient|api.ambient.xyz/v1|",
  "anthropic|Anthropic|api.anthropic.com/v1|claude,fable,opus,sonnet,haiku",
  "any-llm|Any-LLM Control Plane|api.any-llm.com/v1|",
  "anyapi|AnyAPI|api.anyapi.ai/v1|",
  "anyscale|Anyscale Endpoints|api.endpoints.anyscale.com/v1|",
  "apexit|Apertis AI|api.apertis.ai/v1|",
  "aphrodite|Aphrodite Engine|http://localhost:2242/v1|local",
  "apiyi|APIYI|api.apiyi.com/v1|",
  "atomic-chat|Atomic Chat|http://127.0.0.1:1337/v1|local",
  "auriko|Auriko|api.auriko.ai/v1|",
  "azure-foundry|Azure AI Foundry|{resourceName}.services.ai.azure.com/openai/v1|",
  "azure-openai|Azure OpenAI|{resourceName}.openai.azure.com/openai/v1|",
  "baichuan|Baichuan AI|api.baichuan-ai.com/v1|",
  "baidu-qianfan|Baidu Qianfan|qianfan.baidubce.com/v2|",
  "baidu-qianfan-ai|Baidu Qianfan AI|api.baiduqianfan.ai/v1|",
  "bailing|Bailing|api.tbox.cn/api/llm/v1/chat/completions|",
  "baseten|Baseten (Model APIs)|inference.baseten.co/v1|",
  "berget|Berget.AI|api.berget.ai/v1|",
  "bifrost|Bifrost AI|api.bifrost.ai/v1|",
  "bfl|Black Forest Labs|api.bfl.ai/v1|",
  "blueclaw|Blue Claw|openai.blueclaw.network/v1|",
  "braintrust|Braintrust Gateway|api.braintrust.dev/v1|router",
  "byteplus|Byteplus ModelArk|ark.ap-southeast-bytepluses.com/api/v3|",
  "bytez|Bytez|api.bytez.com/v1|",
  "cerebras|Cerebras|api.cerebras.ai/v1|",
  "hyper|Charm Hyper|hyper.charm.land/v1|",
  "chutes|Chutes AI|api.chutes.ai/v1|",
  "clarifai|Clarifai|api.clarifai.com/v2/ext/openai/v1|",
  "claudinio|Claudinio|api.claudin.io/v1|",
  "cline-pass|ClinePass|api.cline.bot/api/v1|",
  "cloudferro-sherlock|CloudFerro Sherlock|api-sherlock.cloudferro.com/openai/v1|",
  "cloudflare-workers-ai|Cloudflare Workers AI|api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1|",
  "cohere|Cohere|api.cohere.ai/compatibility/v1|aya,command",
  "comet-api|Comet API|api.comet.com/v1|",
  "compactifai|CompactifAI|api.compactif.ai/v1|",
  "coralbricks|CoralBricks|inference.coralbricks.ai/v1|",
  "cortecs|Cortecs|api.cortecs.ai/v1|",
  "crof|CrofAI|crof.ai/v1|",
  "crossmodel|CrossModel|api.crossmodel.ai/v1|",
  "drun|D.Run (China)|chat.d.run/v1|",
  "daoxe|DaoXE|daoxe.com/v1|",
  "databricks|Databricks Model Serving|{workspace-url}/serving-endpoints|",
  "datarobot|DataRobot|app.datarobot.com/api/v1|",
  "decart|Decart AI|api.decart.ai/v1|",
  "deepgram|Deepgram (Text)|api.deepgram.com/v1|",
  "deepinfra|DeepInfra|api.deepinfra.com/v1/openai|",
  "deepseek|DeepSeek|api.deepseek.com/v1|",
  "digitalocean|DigitalOcean|inference.do-ai.run/v1|",
  "dinference|DInference|api.dinference.com/v1|",
  "ebcloud|EBCloud|maas-api.ebcloud.com/v1|",
  "edenai|Eden AI|api.edenai.run/v2|",
  "elevenlabs|ElevenLabs (Text)|api.elevenlabs.io/v1|",
  "empiriolabs|EmpirioLabs AI|api.empiriolabs.ai/v1|",
  "evroc|evroc|models.think.evroc.com/v1|",
  "fal|Fal.ai|queue.fal.run|",
  "fastrouter|FastRouter|go.fastrouter.ai/api/v1|router",
  "featherless|Featherless AI|api.featherless.ai/v1|",
  "fireworks|Fireworks AI|api.fireworks.ai/inference/v1|",
  "freemodel|FreeModel|cc.freemodel.dev/v1|",
  "friendli|FriendliAI|api.friendli.ai/v1|",
  "frogbot|FrogBot|app.frogbot.ai/api/v1|",
  "galadriel|Galadriel|api.galadriel.com/v1|",
  "github-copilot|GitHub Copilot|api.githubcopilot.com|",
  "gmi-cloud|GMI Cloud|api.gmicloud.ai/v1|",
  "google|Google AI|generativelanguage.googleapis.com/v1beta/openai|deepmind,gemini,gemma",
  "gcp-vertex|Google Cloud Vertex AI|{region}-aiplatform.googleapis.com/v1/projects/{project_id}/locations/{location}/endpoints/openapi|",
  "gpt4all|GPT4All|http://localhost:4891/v1|local",
  "gradientai|Gradient AI|api.gradient.ai/v1|",
  "greenpt|GreenPT|api.greenpt.ai/v1|",
  "groq|Groq|api.groq.com/openai/v1|",
  "helicone|Helicone|gateway.helicone.ai/v1|router",
  "heroku|Heroku AI|api.heroku.com/ai/v1|",
  "hetzner|Hetzner|inference.hetzner.com/api/v1|",
  "hpc-ai|HPC-AI|api.hpc-ai.com/inference/v1|",
  "huggingface|Hugging Face Inference|router.huggingface.co/v1|hf,router",
  "hyperbolic|Hyperbolic AI|api.hyperbolic.xyz/v1|",
  "ibm-watsonx|IBM watsonx.ai|{region}.ml.cloud.ibm.com/ml/v1|",
  "iflowcn|iFlow|apis.iflow.cn/v1|",
  "impossibl|Impossibl|api.impossibl.com/v1|",
  "inception|Inception AI|api.inception.ai/v1|",
  "inceptron|Inceptron|api.inceptron.io/v1|",
  "inference|Inference|inference.net/v1|",
  "inferx|InferX|model.inferx.net/endpoints/v1|",
  "infomaniak|Infomaniak|api.infomaniak.com/2/ai/${INFOMANIAK_PRODUCT_ID}/openai/v1|",
  "io-net|IO.NET|api.intelligence.io.solutions/api/v1|",
  "jan|Jan (Local)|http://localhost:1337/v1|",
  "jiekou|Jiekou.AI|api.jiekou.ai/openai|",
  "jina|Jina AI|api.jina.ai/v1|",
  "kenari|Kenari|kenari.id/v1|",
  "kilo-gateway|Kilo Gateway|api.kilo.ai/api/gateway|router",
  "kimi|Kimi|api.moonshot.ai/v1|moonshot",
  "kimi-cn|Kimi (CN)|api.moonshot.cn/v1|moonshot",
  "kimi-for-coding|Kimi For Coding|api.kimi.com/coding/v1|moonshot",
  "kluster-ai|Kluster AI|api.kluster.ai/v1|",
  "koboldcpp|KoboldCPP|http://localhost:5001/v1|local",
  "kuae-cloud-coding-plan|KUAE Cloud Coding Plan|coding-plan-endpoint.kuaecloud.net/v1|",
  "lambda-ai|Lambda AI|api.lambda.ai/v1|",
  "laozhang|LaoZhang API|api.laozhang.ai/v1|",
  "lemonade|Lemonade Server|http://localhost:8080/v1|local",
  "lepton|Lepton AI|api.lepton.ai/api/v1|",
  "lilac|Lilac|api.getlilac.com/v1|",
  "litellm-proxy|LiteLLM Proxy|http://localhost:4000/v1|local,router",
  "llama-api|Llama API|api.llama.com/compat/v1|",
  "llama-cpp|llama.cpp / llama-server|http://localhost:8080/v1|local",
  "llamafile|Llamafile|http://localhost:8080/v1|local",
  "llamagate|LlamaGate|api.llamagate.com/v1|",
  "llmgateway|LLM Gateway|api.llmgateway.io/v1|router",
  "llmtr|LLMTR|llmtr.com/v1|",
  "lm-studio|LM Studio (Local)|http://localhost:1234/v1|",
  "localai|LocalAI|http://localhost:8080/v1|",
  "longcat|LongCat|api.longcat.chat/openai|",
  "lucidquery|LucidQuery|api.lucidquery.com/v1|",
  "lynkr|Lynkr|http://127.0.0.1:8081/v1|local",
  "manus|Manus AI|api.manus.ai/v1|",
  "martian|Martian|api.withmartian.com/v1|",
  "meganova|Meganova|api.meganova.ai/v1|",
  "meta|Meta|api.meta.ai/v1|llama",
  "minimax|MiniMax|api.minimax.io/v1|",
  "minimax-cn|MiniMax (CN)|api.minimaxi.com/v1|",
  "minimax-coding-plan|MiniMax Token Plan (minimax.io)|api.minimax.io/anthropic/v1|token-plan",
  "minimax-cn-coding-plan|MiniMax Token Plan (minimaxi.com)|api.minimaxi.com/anthropic/v1|token-plan",
  "mistral|Mistral|api.mistral.ai/v1|codestral,devstral,mixtral",
  "mixlayer|Mixlayer|models.mixlayer.ai/v1|",
  "moark|Moark|moark.com/v1|",
  "modal|Modal|inference.us-west.modal.direct/v1|",
  "model-oracle-ai|Model Oracle AI|api.modeloracle.com/api/v1|",
  "modelis|Modelis|modelishub.com/v1|",
  "modelscope|ModelScope|api-inference.modelscope.cn/v1|",
  "modelslab|ModelsLab|modelslab.com/api/v1|",
  "morph|Morph Chat|api.morph.chat/v1|",
  "nanogpt|NanoGPT|nano-gpt.com/api/v1|",
  "near-ai|NEAR AI Cloud|api.near.ai/v1|",
  "nebius|Nebius Token Factory|api.tokenfactory.nebius.com/v1|",
  "neon|Neon|${NEON_AI_GATEWAY_BASE_URL}/v1|router",
  "neuralwatt|Neuralwatt|api.neuralwatt.com/v1|",
  "new-api|New API|http://localhost:3000/v1|local",
  "nlp-cloud|NLP Cloud|api.nlpcloud.com/v1|",
  "nova|Nova|api.nova.amazon.com/v1|",
  "novita|Novita AI|api.novita.ai/v1|",
  "nscale|Nscale|api.nscale.com/v1|",
  "nvidia|NVIDIA API Catalog|integrate.api.nvidia.com/v1|nim",
  "ofox|Ofox|api.ofox.ai/v1|",
  "ollama|Ollama|http://127.0.0.1:11434|local",
  "ollama-cloud|Ollama Cloud|ollama.com/v1|",
  "one-api|One API|http://localhost:3000/v1|local",
  "opencode-go|OpenCode Go|opencode.ai/zen/go/v1|",
  "opencode|OpenCode Zen|opencode.ai/zen/v1|",
  "openrouter|OpenRouter|openrouter.ai/api/v1|multi-model,router",
  "oracle-oci|Oracle Cloud Infrastructure GenAI|generativeai.oci.oraclecloud.com|",
  "orcarouter|OrcaRouter|api.orcarouter.ai/v1|router",
  "orq|Orq.ai|api.orq.ai/v1|",
  "ovhcloud|OVHcloud AI Endpoints|oai.endpoints.kepler.ai.cloud.ovh.net/v1|",
  "perplexity|Perplexity|api.perplexity.ai|",
  "perplexity-agent|Perplexity Agent|api.perplexity.ai/v1|",
  "petals|Petals|http://localhost:8080|local",
  "pioneer|Pioneer|api.pioneer.ai/v1|",
  "poe|Poe|api.poe.com/v1|",
  "poolside|Poolside|inference.poolside.ai/v1|",
  "portkey|Portkey|api.portkey.ai/v1|",
  "predibase|Predibase|serving.app.predibase.com|",
  "privatemode-ai|Privatemode AI|http://localhost:8080/v1|local",
  "publicai|PublicAI|api.publicai.com/v1|",
  "qihang-ai|QiHang|api.qhaigc.net/v1|",
  "qiniu-ai|Qiniu|api.qnaigc.com/v1|",
  "recraft|Recraft|api.recraft.ai/v1|",
  "regolo-ai|Regolo AI|api.regolo.ai/v1|",
  "replicate|Replicate|api.replicate.com/v1|",
  "requesty|Requesty|api.requesty.ai/v1|",
  "routing-run|routing.run|api.routing.run/v1|",
  "runwayml|RunwayML|api.runwayml.com/v1|",
  "sakana|Sakana AI|api.sakana.ai/v1|",
  "sambanova|SambaNova Cloud|api.sambanova.ai/v1|",
  "sarvam|Sarvam AI|api.sarvam.ai|",
  "scaleway|Scaleway Generative APIs|api.scaleway.ai/v1|",
  "scx|SCX.ai|api.scx.ai/v1|",
  "sensenova|SenseNova|api.sensenova.cn/v1|",
  "sglang|SGLang|http://localhost:30000/v1|local",
  "shareai|ShareAI|api.shareai.now/v1|",
  "siliconflow|SiliconFlow|api.siliconflow.cn/v1|",
  "siliconflow-cn|SiliconFlow (China)|api.siliconflow.cn/v1|",
  "snowflake-cortex|Snowflake Cortex|{account-identifier}.snowflakecomputing.com/api/v1|",
  "spheron|Spheron Network|api.spheron.network/v1|",
  "stability-ai|Stability AI|api.stability.ai/v1|",
  "stackit|STACKIT|api.openai-compat.model-serving.eu01.onstackit.cloud/v1|",
  "stepfun|StepFun|api.stepfun.com/v1|",
  "stepfun-step-plan|StepFun Step Plan (China)|api.stepfun.com/step_plan/v1|",
  "stepfun-ai-step-plan|StepFun Step Plan (Global)|api.stepfun.ai/step_plan/v1|",
  "subconscious|Subconscious|api.subconscious.dev/v1|",
  "submodel|submodel|llm.submodel.ai/v1|",
  "synthetic|Synthetic|api.synthetic.ai/v1|",
  "llmhub|T-Systems LLMhub|llm-server.llmhub.t-systems.net/v2|",
  "tabby|Tabby Coding Assistant|http://localhost:8080/v1|local",
  "telnyx|Telnyx Inference|api.telnyx.com/v2/ai|",
  "tencent-cloud|Tencent Cloud Hunyuan|api.hunyuan.cloud.tencent.com/v1|",
  "tencent-coding-plan|Tencent Coding Plan (China)|api.lkeap.cloud.tencent.com/coding/v3|",
  "tencent-token-plan|Tencent Token Plan|api.lkeap.cloud.tencent.com/plan/v3|token-plan",
  "tencent-tokenhub|Tencent TokenHub|tokenhub.tencentmaas.com/v1|",
  "tensormesh|TensorMesh|api.tensormesh.ai/v1|",
  "tensorx|TensorX|api.tensorx.ai/v1|",
  "tgi|Text Generation Inference (TGI)|http://localhost:8080/v1|local",
  "the-grid-ai|The Grid AI|api.thegrid.ai/v1|",
  "thinkingmachines|Thinking Machines|tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1|",
  "tinfoil|Tinfoil|inference.tinfoil.sh/v1|",
  "together|Together AI|api.together.xyz/v1|",
  "topaz|Topaz AI|api.topaz.ai/v1|",
  "triton-inference|Triton Inference Server|http://localhost:8000/v1|local",
  "trustedrouter|TrustedRouter|api.trustedrouter.com/v1|router",
  "umans-ai|Umans AI|api.code.umans.ai/v1|",
  "umans-ai-coding-plan|Umans AI Coding Plan|api.code.umans.ai/v1|",
  "unify-ai|Unify AI|api.unify.ai/v1|",
  "unorouter|UnoRouter|api.unorouter.com/v1|router",
  "upstage|Upstage AI|api.upstage.ai/v1|",
  "venice|Venice.ai|api.venice.ai/api/v1|",
  "vercel|Vercel AI Gateway|ai-gateway.vercel.sh/v1|router",
  "v0|Vercel v0|api.v0.dev/v1|",
  "vivgrid|Vivgrid|api.vivgrid.com/v1|",
  "vllm|vLLM|http://localhost:8000/v1|local",
  "volcengine|Volcengine (Doubao / Ark)|ark.cn-beijing.volces.com/api/v3|",
  "voyage|Voyage AI|api.voyageai.com/v1|",
  "vultr|Vultr|api.vultrinference.com/v1|",
  "wafer.ai|Wafer|pass.wafer.ai/v1|",
  "wavespeed|WaveSpeed LLM|api.wavespeed.ai/v1|",
  "wandb-inference|Weights & Biases Inference|api.wandb.ai/v1|",
  "writer|Writer API|api.writer.com/v1|",
  "xai|xAI|api.x.ai/v1|grok",
  "xiaomi-mimo|Xiaomi MiMo|platform.xiaomimimo.com/api/v1|",
  "xiaomi-token-plan-cn|Xiaomi Token Plan (China)|token-plan-cn.xiaomimimo.com/v1|token-plan",
  "xiaomi-token-plan-ams|Xiaomi Token Plan (Europe)|token-plan-ams.xiaomimimo.com/v1|token-plan",
  "xiaomi-token-plan-sgp|Xiaomi Token Plan (Singapore)|token-plan-sgp.xiaomimimo.com/v1|token-plan",
  "xinference|Xinference|http://localhost:9997/v1|local",
  "xpersona|Xpersona|www.xpersona.co/v1|",
  "z-ai|Z.ai|api.z.ai/api/paas/v4|glm,zhipu",
  "z-ai-cn|Z.ai (CN)|open.bigmodel.cn/api/paas/v4|glm,zhipu",
  "zai-coding-plan|Z.AI Coding Plan|api.z.ai/api/coding/paas/v4|glm,zhipu",
  "zeldoc|Zeldoc|api.zeldoc.ai/v1|",
  "zenifra|Zenifra|ai.zenifra.com/v1|",
  "zenmux|ZenMux|api.zenmux.com/v1|",
  "zhipuai-coding-plan|Zhipu AI Coding Plan|open.bigmodel.cn/api/coding/paas/v4|glm",
];
export const PROVIDERS: ProviderSpec[] = RAW.map((row) => {
  const i1 = row.indexOf("|"), i2 = row.indexOf("|", i1 + 1), i3 = row.indexOf("|", i2 + 1);
  const kind = row.slice(0, i1), label = row.slice(i1 + 1, i2);
  const u = row.slice(i2 + 1, i3), tagStr = row.slice(i3 + 1);
  const baseUrl = u ? (u.includes("://") || u.startsWith("$") ? u : `https://${u}`) : "";
  return { tags: tagStr ? tagStr.split(",") : [], kind: kind as ProviderKind, label, ...(baseUrl ? { defaultBaseUrl: baseUrl } : {}) };
});
let providerMap: Map<string, ProviderSpec> | undefined;
export function getProviderSpec(kind: ProviderKind): ProviderSpec | undefined {
  if (!providerMap) {
    providerMap = new Map();
    for (const p of PROVIDERS) providerMap.set(p.kind, p);
  }
  return providerMap.get(kind);
}